'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {applySourceOverride,snapshot,register,termsAt}=require('../modules/rental-register');
const source=require('../modules/rental-source.json');
function harness(){let store={receipts:[{id:'RC-1',nature:'PERSONAL',amount:100000,date:'2026-09-30',account:'IndusInd Bank 7883'}],rentals:{tenancies:require('./fixtures/legacy-rentals')(),revision:2}};const routes={};const jobs=register({get:(p,f)=>routes['GET '+p]=f,post:(p,f)=>routes['POST '+p]=f},{loadStore:()=>structuredClone(store),saveStore:s=>store=structuredClone(s),isOwner:()=>true,audit:()=>{},clock:()=>new Date('2026-09-30T12:00:00Z')});function call(body){let status=200,result;routes['POST /api/expenses/rentals']({body,user:{username:'owner'}},{status(n){status=n;return this},json(x){result=x}});return {status,...result};}return {jobs,call,view:()=>snapshot(store,'2026-09-30'),store:()=>store};}
test('source replacement imports only final six floor rows and preserves all supplied amounts and dates',()=>{
 const h=harness();h.jobs.tick();const d=h.view();assert.deepEqual(d.tenancies.map(t=>[t.floor,t.tenant]),[['Top Floor','Ajaybir Singh'],['3rd Floor','Amty Global'],['2nd Floor','Only Supplements'],['1st Floor','Luj O Fab'],['Upper Ground','Nvikk Beauty Private Ltd.'],['Basement','Lujo Fab']]);
 assert.equal(d.tenancies.reduce((n,t)=>n+t.baseRent,0),479475);assert.equal(d.tenancies.reduce((n,t)=>n+t.currentNet,0),517833);assert.equal(d.tenancies.reduce((n,t)=>n+t.securityBalance,0),775000);
 assert.equal(d.tenancies[2].securityOpening,null);assert.equal(d.tenancies[2].securityRecorded,false);assert.equal(d.tenancies[0].startDate,'2026-10-01');assert.equal(d.tenancies[1].endDate,'2029-05-24');assert.equal(d.tenancies[4].source.ownerName,'Nandita Malik');assert.equal(d.tenancies[3].source.increasedRent,'Sep-25');
 assert.ok(d.tenancies.every(t=>t.dueDay===null&&!t.autoEnabled));assert.equal(d.tenancies[1].source.electricityPaymentDate,'19th');assert.equal(d.invoices.length,0);
});
test('source replacement archives previous rental events once and leaves the bank and other books unchanged',()=>{
 const before={tenancies:[{id:'old',tenant:'Fraganote'}],invoices:[{id:'invoice-old',bankDue:1234}],allocations:[{id:'allocation-old',receiptId:'R',amount:200}],deposits:[],revision:3};
 const s={rentals:structuredClone(before),receipts:[{id:'R',amount:500}],expenses:{E:{amount:200}}},bank=structuredClone(s.receipts),expenses=structuredClone(s.expenses);
 assert.equal(applySourceOverride(s,'2026-09-30T12:00:00Z'),true);assert.deepEqual(s.rentalArchives[0].register,before);assert.deepEqual(s.receipts,bank);assert.deepEqual(s.expenses,expenses);assert.deepEqual(s.rentals.allocations,[]);s.rentals.tenancies[0].tenant='Owner correction';assert.equal(applySourceOverride(s,'2026-10-01T12:00:00Z'),false);assert.equal(s.rentalArchives.length,1);assert.equal(s.rentals.tenancies[0].tenant,'Owner correction');
});
test('restarting the scheduler preserves post-import additions and does not repeatedly reset the register',()=>{const h=harness();h.jobs.tick();const r=h.call({action:'add_tenant',tenant:'Later tenant',floor:'Other unit',property:'New property'});assert.equal(r.status,200);h.jobs.tick();assert.equal(h.store().rentalSourceImport,source.id);assert.equal(h.view().tenancies.length,7);assert.equal(h.store().rentalArchives.length,1);});
test('source net payment is preserved without inventing a GST/TDS breakdown',()=>{const h=harness();h.jobs.tick();assert.equal(h.call({action:'invoice',tenancyId:'sheet-third',month:'2026-09',reason:'Agreed full rent'}).status,200);const i=h.view().invoices[0];assert.equal(i.baseRent,76000);assert.equal(i.bankDue,82080);assert.equal(i.taxBreakdownUnknown,true);assert.equal(i.gross,null);assert.equal(h.call({action:'invoice',tenancyId:'sheet-top',month:'2026-09'}).status,400);assert.equal(h.call({action:'invoice',tenancyId:'sheet-third',month:'2026-10',baseRent:38000,reason:'Agreed half-month'}).status,200);assert.equal(h.view().invoices[1].bankDue,41040);});
test('sheet security is available from its as-of date without posting a bank receipt',()=>{const h=harness();h.jobs.tick();h.call({action:'invoice',tenancyId:'sheet-third',month:'2026-09',reason:'Full rent'});const i=h.view().invoices[0],b={action:'security',tenancyId:'sheet-third',invoiceId:i.id,amount:82080,reason:'Owner agreed security adjustment'};assert.equal(h.call({...b,date:'2026-09-29'}).status,400);assert.equal(h.call({...b,date:'2026-09-30'}).status,200);assert.equal(h.view().tenancies[1].securityBalance,67920);assert.equal(h.store().receipts.length,1);});
test('a newly configured increase scales both base and explicitly entered net rent',()=>{const t={baseRent:76000,netRent:82080,escalationDate:'2026-10-01',escalationPercent:5,escalationEveryMonths:12};assert.equal(termsAt(t,'2026-10').baseRent,79800);assert.equal(termsAt(t,'2026-10').netRent,86184);});
