'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {register,state,generate,termsAt,indiaDate,receiptUsage}=require('../modules/rental-register');
function harness(){
  let store={rentalSourceImport:require('../modules/rental-source.json').id,rentals:{tenancies:require('./fixtures/legacy-rentals')()},receipts:[{id:'R1',nature:'PERSONAL',account:'IndusInd Bank 7883',amount:200000,date:'2026-09-01',source:'Tenant'}]},date=new Date('2026-09-30T10:00:00Z'),saves=0;
  const routes={};const job=register({get:(p,f)=>routes['GET '+p]=f,post:(p,f)=>routes['POST '+p]=f},{loadStore:()=>structuredClone(store),saveStore:s=>{store=structuredClone(s);saves++},isOwner:req=>req.user.roles.includes('owner'),audit:()=>{},clock:()=>date});
  function call(body,roles=['owner']){let status=200,result;routes['POST /api/expenses/rentals']({body,user:{username:'test',roles}},{status(n){status=n;return this},json(x){result=x}});return {status,...result};}
  const terms=(overrides={})=>call({action:'terms',tenancyId:'amty-4',baseRent:1000,startMonth:'2026-09',dueDay:31,endDate:'',cgst:9,sgst:9,tds:10,confirmed:true,openingConfirmed:true,autoEnabled:true,autoFrom:'2026-09',...overrides});
  function view(){let result;routes['GET /api/expenses/rentals']({user:{roles:['owner']}},{json:x=>result=x});return result;}
  return {call,terms,view,job,store:()=>store,mutate:f=>f(store),date:d=>date=new Date(d),saves:()=>saves,routes};
}
test('unconfirmed legacy records never auto-generate and reads never write',()=>{const h=harness();h.job.tick();assert.equal(h.view().invoices.length,0);const before=h.saves();h.view();assert.equal(h.saves(),before);assert.equal(h.terms({confirmed:false}).status,400);assert.equal(h.terms({dueDay:''}).status,400);assert.equal(h.terms({openingConfirmed:false}).status,400);});
test('monthly automation is idempotent, clamps due day and catches up after restart',()=>{const h=harness();assert.equal(h.terms().status,200);assert.equal(h.view().invoices.length,1);assert.equal(h.view().invoices[0].dueDate,'2026-09-30');h.job.tick();assert.equal(h.view().invoices.length,1);h.date('2027-02-01T01:00:00Z');h.job.tick();const invoices=h.view().invoices;assert.equal(invoices.length,6);assert.equal(invoices.at(-1).dueDate,'2027-02-28');h.job.tick();assert.equal(h.view().invoices.length,6);assert.equal(h.store().receipts.length,1);});
test('India midnight creates the new month without waiting for UTC midnight',()=>{assert.equal(indiaDate(new Date('2026-09-30T18:29:59Z')),'2026-09-30');assert.equal(indiaDate(new Date('2026-09-30T18:30:00Z')),'2026-10-01');const h=harness();h.terms();h.date('2026-09-30T18:30:00Z');h.job.tick();assert.equal(h.view().invoices.at(-1).month,'2026-10');});
test('new automation cannot silently backfill history and its start stays fixed',()=>{const h=harness();assert.equal(h.terms({autoFrom:'2026-08'}).status,400);h.terms();assert.equal(h.terms({autoFrom:'2026-08'}).status,400);});
test('future tenancy, ended tenancy, paused tenancy and partial months are respected',()=>{const h=harness();h.terms({startDate:'2026-10-12',endDate:'2026-12-12'});assert.equal(h.view().invoices.length,0);h.date('2026-12-01T10:00:00Z');h.job.tick();assert.deepEqual(h.view().invoices.map(i=>i.month),['2026-11']);h.date('2027-01-01T10:00:00Z');h.job.tick();assert.equal(h.view().invoices.length,1);const r=state({});Object.assign(r.tenancies[5],{confirmedAt:'x',autoEnabled:true,autoFrom:'2026-09',dueDay:5,status:'paused'});assert.equal(generate(r,'2026-10-01','now'),0);r.tenancies[5].status='ended';assert.equal(generate(r,'2026-10-01','now'),0);});
test('scheduled annual increases compound with rounded money and preserve issued charges',()=>{const h=harness();h.terms({escalationDate:'2026-10-01',escalationPercent:5,escalationEveryMonths:12});h.date('2027-10-01T00:00:00Z');h.job.tick();const inv=h.view().invoices;assert.equal(inv.find(i=>i.month==='2026-09').baseRent,1000);assert.equal(inv.find(i=>i.month==='2026-10').baseRent,1050);assert.equal(inv.find(i=>i.month==='2027-10').baseRent,1102.5);});
test('future terms take effect in their month; prior terms remain traceable',()=>{const h=harness();h.terms();h.terms({startMonth:'2026-11',baseRent:1500});h.date('2026-11-01T00:00:00Z');h.job.tick();assert.deepEqual(h.view().invoices.map(i=>i.baseRent),[1000,1000,1500]);assert.equal(termsAt(h.store().rentals.tenancies[5],'2026-10').baseRent,1000);});
test('mid-month escalation blocks automated amounts and exposes review issue',()=>{const h=harness();h.terms({escalationDate:'2026-10-15',escalationPercent:5});h.date('2026-10-20T00:00:00Z');h.job.tick();assert.equal(h.view().invoices.length,1);assert.match(h.view().tenancies[5].issues.join(' '),/Mid-month/);});
test('a combined receipt splits across months without double-counting bank money',()=>{const h=harness();h.terms();h.date('2026-10-05T00:00:00Z');h.job.tick();const inv=h.view().invoices;const payload={action:'split_receipt',tenancyId:'amty-4',receiptId:'R1',splits:inv.map(i=>({invoiceId:i.id,amount:i.bankDue})),date:'2026-10-05',reason:'Combined payment'};assert.equal(h.call(payload).status,200);assert.equal(h.store().receipts.length,1);assert.deepEqual(h.view().invoices.map(i=>i.outstanding),[0,0]);assert.equal(h.view().receipts[0].allocated,2160);assert.equal(h.call(payload).status,400);});
test('split validation is atomic and rejects repeated charge ids and overallocations',()=>{const h=harness();h.terms();const i=h.view().invoices[0],base={action:'split_receipt',tenancyId:'amty-4',receiptId:'R1',date:'2026-09-30',reason:'Split'};assert.equal(h.call({...base,splits:[{invoiceId:i.id,amount:10},{invoiceId:i.id,amount:20}]}).status,400);assert.equal(h.call({...base,splits:[{invoiceId:i.id,amount:10},{invoiceId:'missing',amount:20}]}).status,400);assert.equal(h.view().allocations.length,0);});
test('advance reserve, partial use, reversal and release preserve receipt availability',()=>{const h=harness();h.terms();assert.equal(h.call({action:'advance',tenancyId:'amty-4',receiptId:'R1',amount:2000,reason:'Advance'}).status,200);let d=h.view(),c=d.credits[0],i=d.invoices[0];assert.equal(d.receipts[0].available,198000);assert.equal(h.call({action:'credit',tenancyId:'amty-4',creditId:c.id,invoiceId:i.id,amount:500,date:'2026-09-30',reason:'Apply advance'}).status,200);d=h.view();assert.equal(d.invoices[0].outstanding,580);assert.equal(d.credits[0].available,1500);assert.equal(d.receipts[0].available,198000);assert.equal(h.call({action:'reverse',tenancyId:'amty-4',kind:'credit',id:c.id,reason:'Release'}).status,400);assert.equal(h.call({action:'reverse',tenancyId:'amty-4',kind:'allocation',id:d.allocations[0].id,reason:'Wrong month'}).status,200);assert.equal(h.call({action:'reverse',tenancyId:'amty-4',kind:'credit',id:c.id,reason:'Release'}).status,200);assert.equal(h.view().receipts[0].available,200000);assert.equal(receiptUsage(h.store().rentals,'R1'),0);});
test('over-allocation, future settlement and invalid money are rejected',()=>{const h=harness();h.terms();const i=h.view().invoices[0],base={action:'receipt',tenancyId:'amty-4',receiptId:'R1',invoiceId:i.id,date:'2026-09-30',reason:'Rent'};for(const amount of [1081,Infinity,NaN,-1,0])assert.equal(h.call({...base,amount}).status,400);assert.equal(h.call({...base,amount:1,date:'2026-10-01'}).status,400);assert.equal(h.call({...base,amount:1,date:'2026-08-31'}).status,400);});
test('security refunds and corrections cannot create a negative historical balance',()=>{const h=harness();h.terms();const base={tenancyId:'amty-4',reason:'Bank reference'};h.call({...base,action:'deposit',amount:2000,date:'2026-09-20'});assert.equal(h.call({...base,action:'refund_deposit',amount:100,date:'2026-09-19'}).status,400);assert.equal(h.call({...base,action:'refund_deposit',amount:100,date:'2026-09-21'}).status,200);const dep=h.view().deposits.find(d=>d.amount>0);assert.equal(h.call({...base,action:'reverse',kind:'deposit',id:dep.id}).status,400);});
test('voided charges retain history and never silently regenerate',()=>{const h=harness();h.terms();const i=h.view().invoices[0];assert.equal(h.call({action:'void_invoice',tenancyId:'amty-4',invoiceId:i.id,reason:'Wrong amount'}).status,200);h.job.tick();assert.equal(h.view().invoices.length,0);assert.equal(h.view().voidedInvoices.length,1);assert.equal(h.call({action:'invoice',tenancyId:'amty-4',month:'2026-09',baseRent:900,reason:'Corrected charge'}).status,200);assert.equal(h.view().invoices[0].baseRent,900);});
test('reminders use unpaid balance, contact cooldown, grace and promise dates',()=>{const h=harness();h.terms({dueDay:25,graceDays:2});let d=h.view();assert.equal(d.followups.length,1);const i=d.invoices[0];h.call({action:'receipt',tenancyId:'amty-4',invoiceId:i.id,receiptId:'R1',amount:80,date:'2026-09-30',reason:'Part payment'});assert.equal(h.view().followups[0].amount,1000);h.call({action:'followup',tenancyId:'amty-4',invoiceId:i.id,channel:'called',reason:'Spoke to tenant'});assert.equal(h.view().followups.length,0);assert.equal(h.call({action:'followup',tenancyId:'amty-4',invoiceId:i.id,channel:'called',reason:'Duplicate'}).status,400);h.date('2026-10-03T10:00:00Z');assert.equal(h.view().followups.length,1);h.call({action:'pause',tenancyId:'amty-4',invoiceId:i.id,until:'2026-10-05',reason:'Promised payment'});assert.equal(h.view().followups.length,0);h.date('2026-10-06T10:00:00Z');assert.equal(h.view().followups.length,1);h.call({action:'receipt',tenancyId:'amty-4',invoiceId:i.id,receiptId:'R1',amount:1000,date:'2026-10-06',reason:'Balance'});assert.equal(h.view().followups.length,0);});
test('zero and positive opening balances are explicit and cannot be duplicated',()=>{const h=harness();const b={action:'opening',tenancyId:'amty-4',amount:1234,date:'2026-08-31',reason:'Reviewed statement'};assert.equal(h.call(b).status,200);assert.equal(h.call(b).status,400);h.terms();assert.equal(h.view().summary.olderArrears,1234);assert.equal(h.view().summary.due,1080);const h2=harness();assert.equal(h2.call({...b,amount:0}).status,200);assert.equal(h2.view().invoices.length,0);assert.equal(h2.view().tenancies[5].openingConfirmed,true);});
test('revisions prevent stale double-submission and all mutation roles remain owner-only',()=>{const h=harness(),rev=h.view().revision;assert.equal(h.terms({revision:rev}).status,200);assert.equal(h.terms({revision:rev}).status,409);for(const roles of [['admin'],['accounting'],['sales']])assert.equal(h.call({action:'run'},roles).status,403);});
test('rental summary route does not disclose tenant records and rejects nonowners',()=>{const h=harness();let result,status=200;const res={status(n){status=n;return this},json(x){result=x}};h.routes['GET /api/expenses/rentals/summary']({user:{roles:['admin']}},res);assert.equal(status,403);h.routes['GET /api/expenses/rentals/summary']({user:{roles:['owner']}},res);assert.equal(result.tenancies,undefined);assert.equal(result.summary.needsReview,6);});
test('missing or changed linked receipts expose an integrity warning',()=>{const h=harness();h.terms();const i=h.view().invoices[0];h.call({action:'receipt',tenancyId:'amty-4',invoiceId:i.id,receiptId:'R1',amount:500,date:'2026-09-30',reason:'Rent'});h.mutate(s=>s.receipts[0].amount=100);assert.equal(h.view().integrity.length,1);});
test('new properties can be added without creating assumed balances',()=>{const h=harness();const result=h.call({action:'add_tenant',tenant:'New tenant',property:'Another building',floor:'Shop 2'});assert.equal(result.status,200);const t=h.view().tenancies.find(t=>t.id===result.tenancyId);assert.equal(t.property,'Another building');assert.equal(t.confirmedAt,undefined);assert.equal(h.view().invoices.length,0);});

test('contacts can be corrected after the effective month without rewriting historic rent',()=>{const h=harness();h.terms();h.date('2026-10-05T10:00:00Z');assert.equal(h.terms({phone:'+919999999999'}).status,200);assert.equal(h.view().tenancies.find(t=>t.id==='amty-4').phone,'+919999999999');assert.equal(h.terms({baseRent:1500}).status,400);assert.equal(h.view().invoices.find(i=>i.month==='2026-09').baseRent,1000);});

test('logging a promised payment defers reminders until the day after that promise',()=>{const h=harness();h.terms({dueDay:5});const invoiceId=h.view().invoices[0].id;assert.equal(h.call({action:'followup',tenancyId:'amty-4',invoiceId,channel:'called',until:'2026-10-10',reason:'Tenant promised payment'}).status,200);h.date('2026-10-09T10:00:00Z');assert.equal(h.view().followups.length,0);h.date('2026-10-11T10:00:00Z');assert.equal(h.view().followups.length,1);});
