const { test } = require('node:test');
const assert = require('node:assert/strict');
const { submit, canApprove, ready, rackChoices, load, save } = require('../modules/stock-movements');
const fs = require('fs');
const os = require('os');
const path = require('path');
function baseline() { return { version:1, baseline:{reconciled:true,reviewedBy:'owner',reconciledAt:'2026-09-15',racks:{Display:['1','Accesorries'],Warehouse:['5A']}}, positions:[{sku:'SA1',location:'Warehouse',rack:'5A',quantity:3}],movements:[] }; }
function body() { return {requestId:'12345678-1234-4321-8888-123456789012',sku:'sa1',quantity:2,from:{location:'Warehouse',rack:'5A'},to:{location:'Display',rack:'1'}}; }
test('moves preserve total pieces and immediately reflect physical position pending review',()=>{const s=baseline();const m=submit(s,body(),{username:'staff'});assert.equal(m.status,'pending');assert.equal(s.positions[0].quantity,1);assert.equal(s.positions[1].quantity,2);assert.equal(s.positions.reduce((n,p)=>n+p.quantity,0),3);});
test('duplicate submission is idempotent; changed duplicate is rejected',()=>{const s=baseline();submit(s,body(),{username:'staff'});submit(s,body(),{username:'staff'});assert.equal(s.movements.length,1);assert.throws(()=>submit(s,{...body(),quantity:1},{username:'staff'}),/another move/);});
test('unreconciled baseline, anonymous user, invalid quantities and nonexistent racks cannot change stock',()=>{const s=baseline();s.baseline.reconciled=false;assert.equal(ready(s),false);assert.throws(()=>submit(s,body(),{username:'staff'}),/baseline/);s.baseline.reconciled=true;assert.throws(()=>submit(s,body(),{}),/named staff/);for(const q of [0,-1,1.5,'2'])assert.throws(()=>submit(s,{...body(),quantity:q},{username:'staff'}));assert.throws(()=>submit(s,{...body(),to:{location:'Display',rack:'fake'}},{username:'staff'}));assert.equal(s.positions[0].quantity,3);});
test('insufficient source stock and identical positions are rejected',()=>{const s=baseline();assert.throws(()=>submit(s,{...body(),quantity:4},{username:'staff'}),/Not enough/);assert.throws(()=>submit(s,{...body(),to:body().from},{username:'staff'}));});
test('unassigned rack is permitted, correction-required SKU is blocked',()=>{const s=baseline();submit(s,{...body(),to:{location:'Display',rack:''}},{username:'staff'});assert.equal(s.positions[1].rack,'');s.movements[0].status='correction_required';assert.throws(()=>submit(s,{...body(),requestId:'other-unique-request-1234',quantity:1},{username:'staff'}),/correction/);});
test('warehouse users cannot approve; only owner/admin or explicitly assigned managers',()=>{assert.equal(canApprove({role:'warehouse',username:'staff'}),false);assert.equal(canApprove({role:'inventory',username:'staff'}),false);assert.equal(canApprove({role:'admin'}),true);assert.equal(canApprove({roles:['owner']}),true);});
test('atomic store survives reload; corrupt data fails closed',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sanki-move-test-'));const file=path.join(dir,'moves.json');assert.equal(ready(load(file)),false);save(baseline(),file);assert.equal(load(file).positions[0].quantity,3);fs.writeFileSync(file,'broken');assert.throws(()=>load(file));fs.rmSync(dir,{recursive:true});});
test('unreconciled form lists counted racks by location without enabling moves',()=>{const s={version:1,baseline:null,positions:[],movements:[]};const racks=rackChoices(s);assert.equal(ready(s),false);assert.ok(racks.Display.includes('Accesorries'));assert.ok(racks.Display.includes('T1'));assert.ok(racks.Warehouse.includes('5A'));assert.ok(racks.Warehouse.includes('14C'));assert.equal(racks.Warehouse.includes('T1'),false);assert.throws(()=>submit(s,body(),{username:'staff'}),/baseline/);assert.deepEqual(rackChoices(baseline()),baseline().baseline.racks);});
