'use strict';
const express=require('express');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const multer=require('multer');
const {parseBankStatementUpload}=require('./expenses');
const router=express.Router();
const DATA_DIR=process.env.DATA_PATH?path.dirname(process.env.DATA_PATH):path.join(__dirname,'..');
const STORE_PATH=path.join(DATA_DIR,'credit-cards.json');
const EXP_PATH=path.join(DATA_DIR,'expenses.json');
const FILE_DIR=path.join(DATA_DIR,'credit-card-statements');
try{fs.mkdirSync(FILE_DIR,{recursive:true});}catch{}
const upload=multer({storage:multer.diskStorage({destination:(req,file,cb)=>cb(null,FILE_DIR),filename:(req,file,cb)=>cb(null,Date.now()+'-'+crypto.randomBytes(6).toString('hex')+path.extname(file.originalname||'.pdf').toLowerCase())}),limits:{fileSize:15*1024*1024}});
const NATURES=['SANKI','SAMAST','PERSONAL'],CHANNELS=['POS','Website'];
const CLASSIFICATIONS=['expense','refund','card_payment','emi_principal','emi_interest','fee','duplicate','excluded','under_review'];
function num(v){const n=parseFloat(v);return isNaN(n)?0:n;}
function round2(v){return Math.round(num(v)*100)/100;}
function blank(){return{cards:{},statements:{},merchantRules:{
  'meta ads':{pattern:'meta ads',category:'MARKETING EXPENSE',source:'default'},
  shopify:{pattern:'shopify',category:'Subscriptions',source:'default'},
  swiggy:{pattern:'swiggy',category:'FOOD EXPENSE',source:'default'},
  zomato:{pattern:'zomato',category:'FOOD EXPENSE',source:'default'},
  'fuel station':{pattern:'fuel station',category:'Fuel Expenses',source:'default'},
  'late fee':{pattern:'late fee',category:'Fee & Charges',source:'default'},
  interest:{pattern:'interest',category:'Fee & Charges',source:'default'}
},payments:[],audit:[],cardSeq:0,statementSeq:0,paymentSeq:0,auditSeq:0};}
function load(){try{return Object.assign(blank(),JSON.parse(fs.readFileSync(STORE_PATH,'utf8')));}catch{return blank();}}
function save(s){const t=STORE_PATH+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(s));fs.renameSync(t,STORE_PATH);}
function loadExpenses(){try{return JSON.parse(fs.readFileSync(EXP_PATH,'utf8'));}catch{return{};}}
function saveExpenses(s){const postings=new Map();(s.reconciliationExpenses||[]).forEach(x=>postings.set(x.id,x));s.reconciliationExpenses=Array.from(postings.values());const transfers=new Map();(s.transfers||[]).forEach(x=>{const key=x.classification==='credit_card_payment'?[x.note,x.fromAccount,x.amount,x.date].join('|'):x.id;transfers.set(key,x);});s.transfers=Array.from(transfers.values());const t=EXP_PATH+'.tmp-cc-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(s));fs.renameSync(t,EXP_PATH);}
function roles(req){return req.user&&(req.user.roles||(req.user.role?[req.user.role]:[]))||[];}
function allowed(req){return roles(req).some(x=>['admin','owner','accounting'].includes(x));}
function owner(req){return roles(req).some(x=>['admin','owner'].includes(x));}
function guard(req,res,next){return allowed(req)?next():res.status(403).json({success:false,error:'Credit cards are admin/accounting only.'});}
function visibleCard(req,c){return !c.ownerOnly||owner(req);}
function audit(s,req,action,subjectId,details){s.auditSeq=(s.auditSeq||0)+1;s.audit.push({id:'CCA-'+String(s.auditSeq).padStart(6,'0'),at:new Date().toISOString(),by:req.user&&req.user.username||'admin',action,subjectId,details:details||{}});}
function cardName(c){return c.name+' '+c.last4;}
function merchantText(v){return String(v||'').toLowerCase().replace(/\b(?:upi|pos|txn|ref|payment|purchase|debit|credit)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function merchantKey(v){const s=merchantText(v);return s.split(' ').filter(x=>x.length>2&&!/^\d+$/.test(x)).slice(0,3).join(' ');}
function suggestRule(s,narration){const text=merchantText(narration),rules=Object.values(s.merchantRules||{}).filter(r=>text.includes(r.pattern)).sort((a,b)=>b.pattern.length-a.pattern.length);return rules[0]||null;}
function inferClassification(row){const n=String(row.description||'').toLowerCase();if(row.credit){if(/payment|autopay|thank you/.test(n))return'card_payment';return'refund';}if(/emi/.test(n)&&/interest/.test(n))return'emi_interest';if(/emi/.test(n))return'emi_principal';if(/fee|charge|interest|gst/.test(n))return'fee';return'expense';}
function expenseType(name){const n=String(name||'').toLowerCase();if(/rent|salary/.test(n))return'fixed';if(/marketing|advertis|meta|social media|promotion|model|shoot/.test(n))return'marketing';if(/subscription|fee|charge|bank|internet|wifi|technology|telephone|courier|packing|freight/.test(n))return'running';return'variable';}
function statementView(s,st){const card=s.cards[st.cardId],rows=(st.rows||[]).map(r=>Object.assign({},r,{suggested:!!r.suggestedCategory}));return Object.assign({},st,{fileUrl:st.storedName?'/api/expenses/credit-cards/statements/'+encodeURIComponent(st.id)+'/file':'',cardName:card&&cardName(card),rows});}
function liability(s,cardId){const c=s.cards[cardId];let v=num(c&&c.openingOutstanding);Object.values(s.statements||{}).filter(x=>x.cardId===cardId&&x.status==='finalized').forEach(st=>(st.rows||[]).forEach(r=>{if(['duplicate','link','merge','replace'].includes(r.duplicateResolution))return;if(['expense','fee','emi_principal','emi_interest'].includes(r.classification))v+=num(r.amount);if(r.classification==='refund')v-=num(r.amount);if(r.classification==='card_payment')v-=num(r.amount);}));(s.payments||[]).filter(p=>p.cardId===cardId&&p.active!==false).forEach(p=>v-=num(p.amount));return round2(v);}
function duplicateWarnings(exp,cc,row){cc=cc||load();const amount=num(row.amount),date=row.date,n=merchantText(row.narration),found=[];Object.values(exp.expenses||{}).forEach(e=>{if(Math.abs(num(e.amount)-amount)>.01)return;const days=Math.abs((Date.parse(e.date)-Date.parse(date))/86400000);if(days<=2&&(merchantText(e.particulars+' '+e.vendor).includes(n)||n.includes(merchantText(e.particulars+' '+e.vendor))))found.push({kind:'expense',id:e.id,date:e.date,amount:e.amount,label:e.vendor||e.particulars});});(cc.payments||[]).filter(p=>p.active!==false&&Math.abs(num(p.amount)-amount)<.01&&Math.abs((Date.parse(p.date)-Date.parse(date))/86400000)<=2).forEach(p=>found.push({kind:'card_payment',id:p.id,date:p.date,amount:p.amount,label:p.account}));Object.values(cc.statements||{}).filter(st=>st.status==='finalized').forEach(st=>(st.rows||[]).filter(r=>Math.abs(num(r.amount)-amount)<.01&&Math.abs((Date.parse(r.date)-Date.parse(date))/86400000)<=2&&merchantText(r.narration)===n).forEach(r=>found.push({kind:'statement',id:st.id+'/'+r.id,date:r.date,amount:r.amount,label:r.narration})));return found.slice(0,5);}
function rebuildRules(s){const defaults=blank().merchantRules;s.merchantRules=defaults;Object.values(s.statements||{}).filter(st=>st.status==='finalized').sort((a,b)=>String(a.finalizedAt).localeCompare(String(b.finalizedAt))).forEach(st=>st.rows.forEach(r=>{if(!['expense','fee','emi_interest','refund'].includes(r.classification)||!r.category)return;const key=merchantKey(r.narration);if(!key)return;const old=s.merchantRules[key]||{};s.merchantRules[key]={pattern:key,category:r.category,source:'confirmed statement',confirmations:num(old.confirmations)+1,lastConfirmedAt:st.finalizedAt,lastConfirmedBy:st.finalizedBy};}));}
router.use('/api/expenses/credit-cards',guard);
router.get('/api/expenses/credit-cards',(req,res)=>{const s=load(),cards=Object.values(s.cards).filter(c=>visibleCard(req,c)).map(c=>Object.assign({},c,{displayName:cardName(c),outstanding:liability(s,c.id),statementCount:Object.values(s.statements).filter(x=>x.cardId===c.id).length}));res.json({success:true,cards,rules:Object.values(s.merchantRules),classifications:CLASSIFICATIONS,natures:NATURES,channels:CHANNELS,isOwner:owner(req)});});
router.post('/api/expenses/credit-cards',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner/Admin only.'});const s=load(),b=req.body||{},last4=String(b.last4||'').replace(/\D/g,'').slice(-4),name=String(b.name||'').trim();if(!name||last4.length!==4)return res.status(400).json({success:false,error:'Enter card name and last four digits.'});let c=b.id&&s.cards[b.id];if(!c){s.cardSeq=(s.cardSeq||0)+1;c={id:'CC-'+String(s.cardSeq).padStart(4,'0'),createdAt:new Date().toISOString()};}Object.assign(c,{name,last4,cardholder:String(b.cardholder||'').trim(),issuingBank:String(b.issuingBank||'').trim(),cycleDay:Math.max(1,Math.min(31,num(b.cycleDay)||1)),dueDay:Math.max(1,Math.min(31,num(b.dueDay)||1)),creditLimit:round2(b.creditLimit),openingOutstanding:round2(b.openingOutstanding),ownerOnly:!!b.ownerOnly,active:b.active!==false});s.cards[c.id]=c;audit(s,req,b.id?'CARD_UPDATED':'CARD_CREATED',c.id,c);save(s);res.json({success:true,card:Object.assign({},c,{displayName:cardName(c),outstanding:liability(s,c.id)})});});
router.post('/api/expenses/credit-cards/statements/import',upload.single('statement'),async(req,res)=>{const s=load(),card=s.cards[req.body.cardId];if(!req.file||!card||!visibleCard(req,card)){if(req.file)try{fs.unlinkSync(req.file.path);}catch{}return res.status(400).json({success:false,error:'Choose an accessible card and statement file.'});}try{const parsed=await parseBankStatementUpload(req.file.path,req.file.originalname);if(!parsed.length)throw new Error('No dated transactions were found.');s.statementSeq=(s.statementSeq||0)+1;const id='CCS-'+String(s.statementSeq).padStart(5,'0'),exp=loadExpenses(),seen={};const rows=parsed.map((x,i)=>{const narration=String(x.description||'Transaction').trim(),classification=inferClassification(x),rule=suggestRule(s,narration),amount=round2(x.debit||x.credit),base=[x.date,amount,narration].join('|'),occ=seen[base]=(seen[base]||0)+1,rowId='CCR-'+crypto.createHash('sha1').update(base+'|'+occ).digest('hex').slice(0,12);const row={id:rowId,date:x.date,postingDate:x.valueDate||x.date,narration,reference:x.reference||'',amount,debit:round2(x.debit),credit:round2(x.credit),balance:round2(x.balance),classification,category:rule&&['expense','fee','emi_interest'].includes(classification)?rule.category:'',suggestedCategory:rule&&rule.category||'',suggestedRule:rule&&rule.pattern||'',nature:'',channel:'',claimant:'',bill:'',confirmed:false,duplicateResolution:'',linkedExpenseId:''};row.duplicateWarnings=duplicateWarnings(exp,null,row);return row;});const dates=rows.map(x=>x.date).sort();s.statements[id]={id,cardId:card.id,status:'review',originalName:req.file.originalname,storedName:path.basename(req.file.path),mimeType:req.file.mimetype,fileHash:crypto.createHash('sha256').update(fs.readFileSync(req.file.path)).digest('hex'),uploadedAt:new Date().toISOString(),uploadedBy:req.user.username,periodFrom:dates[0],periodTo:dates.at(-1),summary:parsed.statementSummary||{},rows};audit(s,req,'STATEMENT_UPLOADED',id,{cardId:card.id,file:req.file.originalname,rows:rows.length});save(s);res.json({success:true,statement:statementView(s,s.statements[id])});}catch(e){try{fs.unlinkSync(req.file.path);}catch{}res.status(400).json({success:false,error:e.message||'Could not read statement.'});}});
router.post('/api/expenses/credit-cards/statements/manual',(req,res)=>{const s=load(),b=req.body||{},c=s.cards[b.cardId];if(!c||!visibleCard(req,c)||!/^\d{4}-\d{2}-\d{2}$/.test(String(b.date||''))||!(num(b.amount)>0)||!String(b.narration||'').trim())return res.status(400).json({success:false,error:'Choose card, date, narration and amount.'});s.statementSeq=(s.statementSeq||0)+1;const id='CCS-'+String(s.statementSeq).padStart(5,'0'),narration=String(b.narration).trim(),classification=CLASSIFICATIONS.includes(b.classification)?b.classification:'expense',rule=suggestRule(s,narration),isCredit=['refund','card_payment'].includes(classification),row={id:'CCR-'+crypto.randomBytes(6).toString('hex'),date:b.date,postingDate:b.date,narration,reference:String(b.reference||''),amount:round2(b.amount),debit:isCredit?0:round2(b.amount),credit:isCredit?round2(b.amount):0,balance:0,classification,category:rule&&rule.category||'',suggestedCategory:rule&&rule.category||'',suggestedRule:rule&&rule.pattern||'',nature:'',channel:'',claimant:'',bill:'',payingNature:'',payingAccount:'',confirmed:false,duplicateResolution:'',linkedExpenseId:'',duplicateWarnings:duplicateWarnings(loadExpenses(),null,{amount:b.amount,date:b.date,narration})};s.statements[id]={id,cardId:c.id,status:'review',originalName:'Manual entry',storedName:'',mimeType:'',fileHash:'',uploadedAt:new Date().toISOString(),uploadedBy:req.user.username,periodFrom:b.date,periodTo:b.date,summary:{format:'Manual'},rows:[row]};audit(s,req,'MANUAL_STATEMENT_CREATED',id,{cardId:c.id});save(s);res.json({success:true,statement:statementView(s,s.statements[id])});});
router.get('/api/expenses/credit-cards/statements',(req,res)=>{const s=load(),list=Object.values(s.statements).filter(st=>{const c=s.cards[st.cardId];return c&&visibleCard(req,c)&&(!req.query.cardId||st.cardId===req.query.cardId);}).sort((a,b)=>b.uploadedAt.localeCompare(a.uploadedAt)).map(st=>statementView(s,st));res.json({success:true,statements:list});});
router.get('/api/expenses/credit-cards/statements/:id/file',(req,res)=>{const s=load(),st=s.statements[req.params.id],c=st&&s.cards[st.cardId];if(!st||!st.storedName||!c||!visibleCard(req,c))return res.status(404).end();res.type(st.mimeType||path.extname(st.storedName));res.sendFile(path.join(FILE_DIR,st.storedName));});
router.post('/api/expenses/credit-cards/statements/:id/review',(req,res)=>{
  const s=load(),st=s.statements[req.params.id],c=st&&s.cards[st.cardId],items=Array.isArray(req.body&&req.body.rows)?req.body.rows:[];
  if(!st||!c||!visibleCard(req,c)||st.status==='finalized')return res.status(400).json({success:false,error:'Statement is unavailable or finalized.'});
  const byId=Object.fromEntries(items.map(x=>[x.id,x]));
  for(const row of st.rows){
    const b=byId[row.id];if(!b)continue;
    const classification=CLASSIFICATIONS.includes(b.classification)?b.classification:row.classification,nature=NATURES.includes(b.nature)?b.nature:'',channel=CHANNELS.includes(b.channel)?b.channel:'',duplicateResolution=String(b.duplicateResolution||'');
    const duplicateHandled=['duplicate','link','merge','replace'].includes(duplicateResolution);
    if(b.confirmed&&['expense','fee','emi_interest','refund'].includes(classification)&&!duplicateHandled&&(!nature||!String(b.category||'').trim()))return res.status(400).json({success:false,error:'Choose entity and category for '+row.narration+'.'});
    if(b.confirmed&&['expense','fee','emi_interest','refund'].includes(classification)&&!duplicateHandled&&nature!=='PERSONAL'&&!channel)return res.status(400).json({success:false,error:'Choose POS or Website for '+row.narration+'.'});
    if(b.confirmed&&classification==='card_payment'&&!duplicateHandled&&!String(b.payingAccount||'').trim())return res.status(400).json({success:false,error:'Choose the paying bank account for '+row.narration+'.'});
    Object.assign(row,{classification,category:String(b.category||'').trim(),nature,channel:nature==='PERSONAL'?'':channel,claimant:String(b.claimant||'').trim(),bill:String(b.bill||'').trim(),payingNature:NATURES.includes(b.payingNature)?b.payingNature:'',payingAccount:duplicateHandled?'':String(b.payingAccount||'').trim(),confirmed:!!b.confirmed,duplicateResolution,linkedExpenseId:String(b.linkedExpenseId||'').trim()});
  }
  audit(s,req,'STATEMENT_REVIEWED',st.id,{confirmed:st.rows.filter(x=>x.confirmed).length});save(s);res.json({success:true,statement:statementView(s,st)});
});
router.post('/api/expenses/credit-cards/statements/:id/finalize',(req,res)=>{
  const s=load(),st=s.statements[req.params.id],c=st&&s.cards[st.cardId];
  if(!st||!c||!visibleCard(req,c)||st.status==='finalized')return res.status(400).json({success:false,error:'Statement is unavailable or already finalized.'});
  const unresolved=st.rows.filter(r=>!r.confirmed||r.classification==='under_review'||(r.duplicateWarnings.length&&!r.duplicateResolution));
  if(unresolved.length)return res.status(409).json({success:false,error:unresolved.length+' transaction(s) still need confirmation or a duplicate decision.'});
  const exp=loadExpenses();exp.reconciliationExpenses=Array.isArray(exp.reconciliationExpenses)?exp.reconciliationExpenses:[];exp.transfers=Array.isArray(exp.transfers)?exp.transfers:[];exp.transferSeq=num(exp.transferSeq);const now=new Date().toISOString();
  for(const r of st.rows){
    const duplicateHandled=['duplicate','link','merge','replace'].includes(r.duplicateResolution);
    if(['expense','fee','emi_interest','refund'].includes(r.classification)&&!duplicateHandled){
      exp.reconciliationExpenses.push({id:'CCE-'+st.id+'-'+r.id,nature:r.nature,date:r.date,amount:r.classification==='refund'?-r.amount:r.amount,account:cardName(c),category:r.category,type:expenseType(r.category),vendor:r.narration,particulars:r.narration,channel:r.channel||'',claimant:r.claimant||'',billPhoto:r.bill||'',creditCardId:c.id,creditCardStatementId:st.id,creditCardRowId:r.id,createdBy:req.user.username,createdAt:now});
    }
    if(r.classification==='card_payment'&&!duplicateHandled&&r.payingAccount){
      exp.transferSeq++;exp.transfers.push({id:'TR-'+String(exp.transferSeq).padStart(5,'0'),nature:r.payingNature||'SANKI',fromNature:r.payingNature||'SANKI',toNature:r.payingNature||'SANKI',classification:'credit_card_payment',fromAccount:r.payingAccount,toAccount:cardName(c),amount:r.amount,date:r.date,proof:r.bill||'',note:'Credit card statement payment · '+st.id,createdBy:req.user.username,createdAt:now});
    }
  }
  saveExpenses(exp);st.status='finalized';st.finalizedAt=now;st.finalizedBy=req.user.username;
  for(const r of st.rows){if(!['expense','fee','emi_interest','refund'].includes(r.classification)||!r.category)continue;const key=merchantKey(r.narration);if(key){const old=s.merchantRules[key]||{};s.merchantRules[key]={pattern:key,category:r.category,source:'confirmed statement',confirmations:num(old.confirmations)+1,lastConfirmedAt:now,lastConfirmedBy:req.user.username};}}
  audit(s,req,'STATEMENT_FINALIZED',st.id,{rows:st.rows.length,cardId:c.id});save(s);res.json({success:true,statement:statementView(s,st),outstanding:liability(s,c.id)});
});
router.post('/api/expenses/credit-cards/statements/:id/reopen',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner/Admin only.'});const s=load(),st=s.statements[req.params.id],reason=String(req.body&&req.body.reason||'').trim();if(!st||st.status!=='finalized'||!reason)return res.status(400).json({success:false,error:'Choose a finalized statement and enter a correction reason.'});const exp=loadExpenses(),before={status:st.status,finalizedAt:st.finalizedAt,finalizedBy:st.finalizedBy};exp.reconciliationExpenses=(exp.reconciliationExpenses||[]).filter(x=>x.creditCardStatementId!==st.id);exp.transfers=(exp.transfers||[]).filter(x=>!String(x.note||'').includes('Credit card statement payment · '+st.id));saveExpenses(exp);st.status='review';st.reopenedAt=new Date().toISOString();st.reopenedBy=req.user.username;st.reopenReason=reason;delete st.finalizedAt;delete st.finalizedBy;rebuildRules(s);audit(s,req,'STATEMENT_REOPENED',st.id,{reason,before,after:{status:'review'}});save(s);res.json({success:true,statement:statementView(s,st),outstanding:liability(s,st.cardId)});});
router.post('/api/expenses/credit-cards/payments',(req,res)=>{const s=load(),b=req.body||{},c=s.cards[b.cardId],amount=round2(b.amount),nature=NATURES.includes(b.nature)?b.nature:'SANKI';if(!c||!visibleCard(req,c)||!(amount>0)||!String(b.account||'').trim()||!/^\d{4}-\d{2}-\d{2}$/.test(String(b.date||'')))return res.status(400).json({success:false,error:'Choose card, paying account, amount and date.'});s.paymentSeq=(s.paymentSeq||0)+1;const p={id:'CCP-'+String(s.paymentSeq).padStart(5,'0'),cardId:c.id,amount,date:b.date,nature,account:String(b.account).trim(),paymentKind:['full','minimum','partial','excess'].includes(b.paymentKind)?b.paymentKind:'partial',proof:String(b.proof||''),reference:String(b.reference||''),createdAt:new Date().toISOString(),createdBy:req.user.username,active:true};s.payments.push(p);const exp=loadExpenses();exp.transfers=Array.isArray(exp.transfers)?exp.transfers:[];exp.transferSeq=num(exp.transferSeq)+1;exp.transfers.push({id:'TR-'+String(exp.transferSeq).padStart(5,'0'),nature,fromNature:nature,toNature:nature,classification:'credit_card_payment',fromAccount:p.account,toAccount:cardName(c),amount,date:p.date,proof:p.proof,note:'Credit card payment '+p.id+(p.reference?' · '+p.reference:''),creditCardPaymentId:p.id,createdBy:req.user.username,createdAt:p.createdAt});saveExpenses(exp);audit(s,req,'CARD_PAYMENT_RECORDED',p.id,p);save(s);res.json({success:true,payment:p,outstanding:liability(s,c.id)});});
router.get('/api/expenses/credit-cards/:id/ledger',(req,res)=>{const s=load(),c=s.cards[req.params.id];if(!c||!visibleCard(req,c))return res.status(404).json({success:false,error:'Card not found.'});const entries=[{id:'OPENING',date:'',description:'Opening outstanding',debit:num(c.openingOutstanding),credit:0}];Object.values(s.statements).filter(st=>st.cardId===c.id&&st.status==='finalized').forEach(st=>st.rows.forEach(r=>{if(['duplicate','link','merge','replace'].includes(r.duplicateResolution))return;if(['expense','fee','emi_principal','emi_interest'].includes(r.classification))entries.push({id:r.id,date:r.date,description:r.narration,debit:r.amount,credit:0,statementId:st.id});if(['refund','card_payment'].includes(r.classification))entries.push({id:r.id,date:r.date,description:r.narration,debit:0,credit:r.amount,statementId:st.id});}));s.payments.filter(p=>p.cardId===c.id&&p.active!==false).forEach(p=>entries.push({id:p.id,date:p.date,description:p.paymentKind+' card payment from '+p.account,debit:0,credit:p.amount,proof:p.proof}));entries.sort((a,b)=>String(a.date+a.id).localeCompare(String(b.date+b.id)));let balance=0;entries.forEach(e=>{balance+=num(e.debit)-num(e.credit);e.balance=round2(balance);});res.json({success:true,card:Object.assign({},c,{displayName:cardName(c)}),outstanding:round2(balance),entries:entries.slice().reverse()});});
module.exports={router,merchantKey,inferClassification};
