const express=require('express'),https=require('https'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{userSummary}=require('./auth-users');
const {createWorker}=require('tesseract.js'),eng=require('@tesseract.js-data/eng');
const router=express.Router(),DIR=process.env.DATA_PATH?path.dirname(process.env.DATA_PATH):path.join(__dirname,'..'),FILE=path.join(DIR,'telegram.json');
function blank(){return{chats:{},userChats:{},linkCodes:{},webhookSecret:'',botUsername:'',updates:0};}
function load(){try{return Object.assign(blank(),JSON.parse(fs.readFileSync(FILE,'utf8')));}catch{return blank();}}
function save(s){const t=FILE+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(s));fs.renameSync(t,FILE);}
function token(){return String(process.env.TELEGRAM_BOT_TOKEN||'').trim();} function configured(){return!!token();}
function base(){return String(process.env.PUBLIC_URL||(process.env.RAILWAY_PUBLIC_DOMAIN?'https://'+process.env.RAILWAY_PUBLIC_DOMAIN:'')||'https://sanki-ops.up.railway.app').replace(/\/$/,'');}
function esc(v){return String(v==null?'':v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function roles(q){return(q.user&&(q.user.roles||(q.user.role?[q.user.role]:[])))||[];} function owner(q){return roles(q).includes('owner');}
function tgOnce(method,payload){return new Promise(resolve=>{if(!configured())return resolve({ok:false,description:'Telegram is not configured'});const data=JSON.stringify(payload||{}),q=https.request({hostname:'api.telegram.org',path:'/bot'+token()+'/'+method,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>{try{resolve(JSON.parse(b));}catch{resolve({ok:false,description:'Invalid response from Telegram'});}});});q.setTimeout(10000,()=>q.destroy(new Error('Telegram request timed out')));q.on('error',e=>resolve({ok:false,description:e&&e.message||'Telegram request failed'}));q.write(data);q.end();});}
function tg(method,payload){let attempt=0;const run=()=>tgOnce(method,payload).then(result=>{attempt++;if(result&&result.ok)return result;if(attempt<3)return new Promise(resolve=>setTimeout(resolve,attempt*750)).then(run);console.warn('[telegram] '+method+' failed after '+attempt+' attempts: '+String(result&&result.description||'unknown error'));return result||{ok:false};});return run();}
function payload(text,opts){const p={text,parse_mode:'HTML',disable_web_page_preview:true},b=opts&&opts.button;if(b){const target=b.url||b.path||'',url=/^https?:\/\//.test(target)?target:base()+(target.startsWith('/')?target:'/'+target);p.reply_markup={inline_keyboard:[[{text:b.text||'Open in app',url}]]};}return p;}
function notify(text,opts){const ids=Object.keys(load().chats||{});if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyApprovers(nature,text,opts){const s=load(),wanted=String(nature||'SANKI').toUpperCase(),ids=Object.keys(s.chats||{}).filter(id=>{const target=userSummary(s.chats[id]&&s.chats[id].name),r=target&&target.roles||[];if(wanted==='PERSONAL')return r.includes('owner');if(r.includes('admin')||r.includes('owner'))return true;if(wanted==='SAMAST')return r.includes('samast_accounting');return r.includes('accounting');});if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyUser(username,text,opts){const id=load().userChats[String(username||'').toLowerCase()];if(!configured()||!id)return Promise.resolve({sent:0});return tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))).then(r=>({sent:r&&r.ok?1:0})).catch(()=>({sent:0}));}
function parsePersonalCaption(raw){
  const text=String(raw||'').trim();
  if(!/^\/?personal\b/i.test(text))return{ok:false,error:'Start the narration with Personal.'};
  if(!text.includes('|')){
    let body=text.replace(/^\/?personal\b/i,'').trim(),datePart=(body.match(/\b\d{4}-\d{2}-\d{2}\b/)||[])[0]||'';
    const accountMatch=body.match(/\bcash\b|\b\d{4}\b/i),accountPart=accountMatch?accountMatch[0]:'';
    const marked=body.match(/(?:₹|\brs\.?\b|\binr\b)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/i),numbers=body.match(/\b[0-9][0-9,]*(?:\.\d{1,2})?\b/g)||[];
    const candidates=numbers.filter(x=>x!==accountPart&&!datePart.includes(x)),amountText=marked?marked[1]:(candidates[candidates.length-1]||''),amount=Number(String(amountText).replace(/,/g,''));
    let narration=body;if(datePart)narration=narration.replace(datePart,' ');if(accountPart)narration=narration.replace(accountPart,' ');if(marked)narration=narration.replace(marked[0],' ');else if(amountText)narration=narration.replace(new RegExp('\\b'+amountText.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b'),' ');narration=narration.replace(/[|,;-]+/g,' ').replace(/\s+/g,' ').trim();
    if(!narration)return{ok:false,error:'Add a short purpose or vendor narration.'};if(!accountPart)return{ok:false,error:'Add the account last four digits.'};if(!(amount>0))return{ok:false,error:'Add the payment amount.'};
    return{ok:true,amount,account:accountPart,particulars:narration,date:datePart};
  }
  const parts=text.split('|').map(x=>x.trim()).filter(Boolean);
  const amountPart=parts.find((x,i)=>i>0&&/(?:₹|\brs\.?\b|\binr\b)\s*[0-9]/i.test(x))||parts.find((x,i)=>i>0&&/^\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/.test(x)&&!/^\d{4}$/.test(x)),amountMatch=amountPart&&amountPart.match(/([0-9][0-9,]*(?:\.\d{1,2})?)/),amount=amountMatch?Number(amountMatch[1].replace(/,/g,'')):0;
  const accountPart=parts.find((x,i)=>i>0&&(/\b\d{4}\b/.test(x)||/cash/i.test(x)))||'';
  const datePart=parts.find(x=>/^\d{4}-\d{2}-\d{2}$/.test(x))||'';
  const narration=parts.slice(1).filter(x=>x!==accountPart&&x!==datePart&&x!==amountPart).join(' | ').trim();
  if(!narration)return{ok:false,error:'Add a short purpose or vendor narration.'};
  if(!accountPart)return{ok:false,error:'Add the account name or its last four digits.'};
  if(!(amount>0))return{ok:false,error:'Add the payment amount.'};
  return{ok:true,amount,account:accountPart,particulars:narration,date:datePart};
}
function parsePersonalIntent(raw){
  const text=String(raw||'').trim();if(!/^\/?personal\b/i.test(text))return{ok:false,error:'Start the narration with Personal.'};const received=/\breceived\b/i.test(text),cash=/^\/?personal\s+cash\b/i.test(text),upi=/\bupi\b/i.test(text);
  let particulars=text.replace(/^\/?personal\b/i,'').replace(/\b(?:cash|upi|received)\b/ig,' ').replace(/(?:₹|\brs\.?\b|\binr\b)\s*[0-9][0-9,]*(?:\.\d{1,2})?/ig,' ').replace(/\b\d{4}-\d{2}-\d{2}\b/g,' ').replace(/\b[0-9][0-9,]*(?:\.\d{1,2})?\b/g,' ').replace(/[|,;-]+/g,' ').replace(/\s+/g,' ').trim();
  return particulars?{ok:true,particulars,received,cash,upi}:{ok:false,error:'Add a short purpose or vendor narration.'};
}
function parsePaymentOcr(raw){
  const text=String(raw||''),clean=text.replace(/\r/g,''),lines=clean.split('\n').map(x=>x.trim()).filter(Boolean),pi=lines.findIndex(x=>/paid\s+to/i.test(x)),paidLine=pi>=0?([lines[pi].replace(/^.*?paid\s+to\s*/i,''),lines[pi+1]||''].join(' ')):'',paid=(paidLine.match(/(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)\s*$/i)||clean.match(/(?:₹|rs\.?|inr)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/i)||[])[1]||'',amount=Number(paid.replace(/,/g,''))||0;
  const debited=(clean.match(/debited\s+from[\s\S]{0,120}?(?:x+|\*+|•+)?\s*(\d{2,4})\b/i)||clean.match(/(?:x{2,}|\*{2,}|•{2,})\s*(\d{2,4})\b/i)||[])[1]||'';
  let recipient='';if(pi>=0){recipient=lines[pi].replace(/^.*?paid\s+to\s*/i,'').replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').trim();if(!recipient&&lines[pi+1])recipient=lines[pi+1].replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').replace(/^[^A-Za-z]+/,'').trim();}
  const months={january:'01',february:'02',march:'03',april:'04',may:'05',june:'06',july:'07',august:'08',september:'09',october:'10',november:'11',december:'12'},dm=clean.match(/\b(\d{1,2})\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(20\d{2})\b/i),date=dm?dm[3]+'-'+months[dm[2].toLowerCase()]+'-'+String(dm[1]).padStart(2,'0'):'';
  return{amount,account:debited,recipient,date,text:clean};
}
function parseReceiptOcr(raw){
  const base=parsePaymentOcr(raw),text=String(raw||'').replace(/\r/g,''),lines=text.split('\n').map(x=>x.trim()).filter(Boolean),ri=lines.findIndex(x=>/received\s+from/i.test(x)),receivedLine=ri>=0?[lines[ri].replace(/^.*?received\s+from\s*/i,''),lines[ri+1]||''].join(' '):'',amountText=(receivedLine.match(/(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)\s*$/i)||text.match(/(?:₹|rs\.?|inr)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/i)||[])[1]||'',credited=(text.match(/credited\s+(?:to|in)[\s\S]{0,120}?(?:x+|\*+|•+)?\s*(\d{2,4})\b/i)||text.match(/(?:x{2,}|\*{2,}|•{2,})\s*(\d{2,4})\b/i)||[])[1]||'';let source='';if(ri>=0){source=lines[ri].replace(/^.*?received\s+from\s*/i,'').replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').trim();if(!source&&lines[ri+1])source=lines[ri+1].replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').replace(/^[^A-Za-z]+/,'').trim();}
  return{amount:Number(amountText.replace(/,/g,''))||base.amount,account:credited,source,date:base.date,text};
}
function inferPersonalCategory(narration,recipient){
  const t=(String(narration||'')+' '+String(recipient||'')).toLowerCase(),rules=[
    ['Food & Dining',/food|dining|restaurant|cafe|coffee|grocery|meal|lunch|dinner|breakfast|tip\b/],['Household Staff',/nanny|maid|driver|cook|helper|domestic|house staff|salary/],['Children & Education',/school|tuition|education|book|child|kid|uniform/],['Medical & Healthcare',/doctor|hospital|medicine|medical|pharmacy|clinic|health/],['Travel & Transport',/uber|ola|rapido|fuel|petrol|diesel|travel|flight|train|taxi|parking/],['Home & Utilities',/electricity|water|rent|repair|plumber|carpenter|home|utility|internet|broadband/],['Shopping',/amazon|myntra|clothes|shopping|purchase/],['Subscriptions',/subscription|netflix|spotify|software|membership/],['Personal Care',/salon|gym|spa|personal care|beauty/],['Gifts & Charity',/gift|donation|charity/],['Entertainment',/movie|cinema|game|entertainment/],['Financial Charges',/bank charge|fee|interest|penalty/]
  ];for(const r of rules)if(r[1].test(t))return{ledger:r[0],confidence:true};return{ledger:'Miscellaneous Personal',confidence:false};
}
let workerPromise;function ocrWorker(){if(!workerPromise)workerPromise=createWorker(eng.code,1,{langPath:eng.langPath,gzip:eng.gzip,cacheMethod:'none'});return workerPromise;}
async function readPaymentScreenshot(filePath){const worker=await ocrWorker(),result=await worker.recognize(filePath);return parsePaymentOcr(result&&result.data&&result.data.text||'');}
function downloadPhoto(fileId){
  return tg('getFile',{file_id:fileId}).then(info=>new Promise((resolve,reject)=>{
    const remote=info&&info.ok&&info.result&&info.result.file_path;if(!remote)return reject(new Error('Telegram could not provide the image.'));
    const ext=(path.extname(remote)||'.jpg').toLowerCase().replace(/[^.a-z0-9]/g,'')||'.jpg',dir=path.join(DIR,'expense-proofs');try{fs.mkdirSync(dir,{recursive:true});}catch{}
    const name='personal-tg-'+Date.now()+'-'+crypto.randomBytes(6).toString('hex')+ext,fp=path.join(dir,name);
    https.get({hostname:'api.telegram.org',path:'/file/bot'+token()+'/'+remote},r=>{const chunks=[];let size=0;r.on('data',c=>{size+=c.length;if(size>15*1024*1024)r.destroy(new Error('Image is too large.'));else chunks.push(c);});r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)return reject(new Error('Telegram image download failed.'));fs.writeFileSync(fp,Buffer.concat(chunks));resolve({url:'/api/expenses/photo/'+name,filePath:fp});});r.on('error',reject);}).on('error',reject);
  }));
}
function linkedUsername(s,chatId){return Object.keys(s.userChats||{}).find(u=>String(s.userChats[u])===String(chatId))||'';}
function reply(chatId,text){return tg('sendMessage',{chat_id:chatId,text});}
async function handleWebhookMessage(msg,s){
  if(!msg||!msg.chat)return;const id=String(msg.chat.id),raw=String(msg.caption||msg.text||'').trim(),m=raw.match(/^\/start(?:@\w+)?\s+([a-f0-9]{32})$/i),link=m&&s.linkCodes[m[1]];
  if(link&&Date.now()<link.expiresAt){s.userChats[String(link.username).toLowerCase()]=id;if(link.approver)s.chats[id]={id,name:link.username,at:new Date().toISOString()};delete s.linkCodes[m[1]];save(s);return reply(id,'✅ Telegram linked to your SANKI account. Expense updates will arrive here.');}
  if(/^\/stop\b/i.test(raw)){delete s.chats[id];Object.keys(s.userChats).forEach(u=>{if(s.userChats[u]===id)delete s.userChats[u];});save(s);return reply(id,'🔕 SANKI notifications disconnected.');}
  const username=linkedUsername(s,id),target=username&&userSummary(username),isOwner=target&&target.roles&&target.roles.includes('owner');
  const photos=Array.isArray(msg.photo)?msg.photo:[],document=msg.document&&/^image\//.test(String(msg.document.mime_type||''))?msg.document:null,file=(photos.length?photos[photos.length-1]:document);
  if(file){
    if(msg.chat.type&&msg.chat.type!=='private')return reply(id,'🔒 Personal expense capture works only in your private bot chat.');
    if(!isOwner)return reply(id,'🔒 Only the linked Owner account can create PERSONAL expenses from Telegram.');
    const intent=parsePersonalIntent(raw);if(!intent.ok)return reply(id,'Could not record this yet: '+intent.error+'\n\nEasy format: Personal Food tip');
    const supplied=parsePersonalCaption(raw),download=await downloadPhoto(file.file_id),sourceKey='telegram:'+id+':'+String(file.file_unique_id||file.file_id);let ocr={};try{ocr=await readPaymentScreenshot(download.filePath);}catch(e){console.error('[telegram] OCR failed:',e.message);}
    if(intent.received){const receiptOcr=parseReceiptOcr(ocr.text||''),amount=intent.cash&&supplied.ok?supplied.amount:receiptOcr.amount,account=intent.cash?'cash':receiptOcr.account,date=receiptOcr.date||'',source=intent.particulars;if(!(amount>0)||!account){try{fs.unlinkSync(download.filePath);}catch{}return reply(id,'I could not clearly read '+(!(amount>0)?'the received amount':'the receiving account')+'.\n\nCash example: Personal Cash Received Sale of old furniture 27500\nUPI example: Personal UPI Received Refund from Mukesh');}const result=require('./expenses').createTelegramPersonalReceipt({amount,account,date,source,username:target.username,proof:download.url,sourceKey,ocrText:receiptOcr.text});if(!result.success)return reply(id,'Could not record this receipt: '+result.error);const x=result.receipt;return reply(id,(result.duplicate?'Already recorded':'✅ PERSONAL money received recorded')+'\n'+x.id+' · ₹'+Math.round(x.amount)+' · '+x.source+'\nReceived in: '+x.account);}
    const amount=intent.cash&&supplied.ok?supplied.amount:(supplied.ok?supplied.amount:ocr.amount),account=intent.cash?'cash':(supplied.ok?supplied.account:ocr.account),date=(supplied.ok&&supplied.date)||ocr.date||'',particulars=supplied.ok?supplied.particulars:intent.particulars,category=inferPersonalCategory(particulars,ocr.recipient);
    if(!(amount>0)||!account){try{fs.unlinkSync(download.filePath);}catch{}return reply(id,'I could not clearly read '+(!(amount>0)?'the amount':'the paying account')+' from this screenshot. Please send a clearer screenshot, or add '+(!(amount>0)?'the amount':'the account last digits')+' after the narration.\n\nExample: Personal Food tip'+(!(amount>0)?' 200':' 0993'));}
    const result=require('./expenses').createTelegramPersonalExpense({amount,account,date,particulars,vendor:ocr.recipient||particulars,ledger:category.ledger,needsReview:!category.confidence,ocrText:ocr.text,username:target.username,proof:download.url,sourceKey,rawNarration:raw});
    if(!result.success)return reply(id,'Could not record this yet: '+result.error+'\n\nEasy format: Personal Food tip');
    const e=result.expense;return reply(id,(result.duplicate?'Already recorded':'✅ PERSONAL expense recorded and marked paid')+'\n'+e.id+' · ₹'+Math.round(e.amount)+' · '+e.particulars+'\nPaid to: '+e.vendor+'\nAccount: '+e.account+'\nCategory: '+e.ledger+(e.telegramNeedsReview?' (please review)':'')+'\nYou can correct it later in PERSONAL → All expenses.');
  }
  if(username)return reply(id,'To record a PERSONAL payment, attach its screenshot with a simple caption like:\nPersonal Food tip');
  return reply(id,'Ask the Owner for a fresh SANKI Telegram linking link.');
}
router.post('/api/telegram/webhook/:secret',express.json(),(req,res)=>{const s=load(),header=req.get('x-telegram-bot-api-secret-token')||'';if(!s.webhookSecret||(req.params.secret!==s.webhookSecret&&header!==s.webhookSecret))return res.status(403).end();s.updates++;save(s);const msg=(req.body||{}).message||(req.body||{}).edited_message;res.json({ok:true});handleWebhookMessage(msg,s).catch(e=>{console.error('[telegram] webhook message failed:',e.message);if(msg&&msg.chat)reply(String(msg.chat.id),'Could not record that screenshot. Please try again.');});});
router.post('/api/telegram/link',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});if(!configured())return res.json({success:true,configured:false,username:target.username,url:'',expiresInMinutes:15});const finish=botUsername=>{if(!botUsername)return res.json({success:false,configured:true,error:'Could not identify the configured Telegram bot.'});const s=load(),code=crypto.randomBytes(16).toString('hex');s.botUsername=botUsername;s.linkCodes[code]={username:target.username,approver:target.roles.some(r=>['admin','owner','accounting','samast_accounting'].includes(r)),expiresAt:Date.now()+900000};Object.keys(s.linkCodes).forEach(k=>{if(s.linkCodes[k].expiresAt<Date.now())delete s.linkCodes[k];});save(s);res.json({success:true,configured:true,username:target.username,url:'https://t.me/'+botUsername+'?start='+code,expiresInMinutes:15});};const known=load().botUsername;if(known)return finish(known);tg('getMe',{}).then(me=>finish(me&&me.ok?me.result.username:''));});
router.get('/api/telegram/status',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const s=load(),localUrl=base()+'/api/telegram/webhook/';if(!configured())return res.json({success:true,configured:false,webhookSet:false,connectedToThisApp:false,subscribers:Object.keys(s.chats).length,linkedUsers:Object.keys(s.userChats).length,linkedUsernames:Object.keys(s.userChats),botUsername:s.botUsername||''});Promise.all([tg('getMe',{}),tg('getWebhookInfo',{})]).then(([me,hook])=>{const currentUrl=hook&&hook.ok&&hook.result?String(hook.result.url||''):'';res.json({success:true,configured:true,webhookSet:!!currentUrl,connectedToThisApp:currentUrl.startsWith(localUrl),pendingUpdates:hook&&hook.ok&&hook.result?Number(hook.result.pending_update_count||0):null,subscribers:Object.keys(s.chats).length,linkedUsers:Object.keys(s.userChats).length,linkedUsernames:Object.keys(s.userChats),botUsername:me&&me.ok?me.result.username:(s.botUsername||'')});}).catch(()=>res.status(502).json({success:false,error:'Could not inspect the Telegram bot.'}));});
router.post('/api/telegram/setup',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});if(!configured())return res.json({success:false,error:'TELEGRAM_BOT_TOKEN is not configured on Railway.'});const s=load();if(!s.webhookSecret)s.webhookSecret=crypto.randomBytes(24).toString('hex');Promise.all([tg('getMe',{}),tg('setWebhook',{url:base()+'/api/telegram/webhook/'+s.webhookSecret,secret_token:s.webhookSecret,allowed_updates:['message']})]).then(([me,hook])=>{if(me&&me.ok)s.botUsername=me.result.username;save(s);res.json(hook&&hook.ok?{success:true,botUsername:s.botUsername}:{success:false,error:(hook&&hook.description)||'Webhook setup failed.'});});});
router.post('/api/telegram/test',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const username=String(req.body&&req.body.username||'').trim();if(username){const target=userSummary(username);if(!target)return res.status(404).json({success:false,error:'User not found.'});return notifyUser(target.username,'🔔 <b>Your SANKI Telegram notifications are working.</b>').then(r=>res.json(r.sent?{success:true,sent:r.sent,username:target.username}:{success:false,sent:0,error:'This user has not linked Telegram yet.'}));}notify('🔔 <b>SANKI Telegram notifications are working.</b>').then(r=>res.json({success:true,sent:r.sent}));});
router.post('/api/telegram/unlink',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});const s=load(),key=target.username.toLowerCase(),chatId=s.userChats[key];delete s.userChats[key];if(chatId&&!Object.values(s.userChats).includes(chatId))delete s.chats[chatId];save(s);res.json({success:true,username:target.username,wasLinked:!!chatId});});
module.exports={router,notify,notifyApprovers,notifyUser,esc,configured,parsePersonalCaption,parsePersonalIntent,parsePaymentOcr,parseReceiptOcr,inferPersonalCategory,readPaymentScreenshot};
