const express=require('express'),https=require('https'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{userSummary}=require('./auth-users');
const router=express.Router(),DIR=process.env.DATA_PATH?path.dirname(process.env.DATA_PATH):path.join(__dirname,'..'),FILE=path.join(DIR,'telegram.json');
function blank(){return{chats:{},userChats:{},linkCodes:{},webhookSecret:'',botUsername:'',updates:0};}
function load(){try{return Object.assign(blank(),JSON.parse(fs.readFileSync(FILE,'utf8')));}catch{return blank();}}
function save(s){const t=FILE+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(s));fs.renameSync(t,FILE);}
function token(){return String(process.env.TELEGRAM_BOT_TOKEN||'').trim();} function configured(){return!!token();}
function base(){return String(process.env.PUBLIC_URL||(process.env.RAILWAY_PUBLIC_DOMAIN?'https://'+process.env.RAILWAY_PUBLIC_DOMAIN:'')||'https://sanki-ops.up.railway.app').replace(/\/$/,'');}
function esc(v){return String(v==null?'':v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function roles(q){return(q.user&&(q.user.roles||(q.user.role?[q.user.role]:[])))||[];} function owner(q){return roles(q).includes('owner');}
function tgOnce(method,payload){return new Promise(resolve=>{if(!configured())return resolve({ok:false,description:'Telegram is not configured'});const data=JSON.stringify(payload||{}),q=https.request({hostname:'api.telegram.org',path:'/bot'+token()+'/'+method,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>{try{resolve(JSON.parse(b));}catch{resolve({ok:false,description:'Invalid response from Telegram'});}});});q.setTimeout(10000,()=>q.destroy(new Error('Telegram request timed out')));q.on('error',e=>resolve({ok:false,description:e&&e.message||'Telegram request failed'}));q.write(data);q.end();});}
function tg(method,payload){let attempt=0;const run=()=>tgOnce(method,payload).then(result=>{attempt++;if(result&&result.ok)return result;if(attempt<3)return new Promise(resolve=>setTimeout(resolve,attempt*750)).then(run);console.warn('[telegram] '+method+' failed after '+attempt+' attempts: '+String(result&&result.description||'unknown error'));return result||{ok:false};});return run();}
function payload(text,opts){const p={text,parse_mode:'HTML',disable_web_page_preview:true},b=opts&&opts.button;if(b){const target=b.url||b.path||'',url=/^https?:\/\//.test(target)?target:base()+(target.startsWith('/')?target:'/'+target);p.reply_markup={inline_keyboard:[[{text:b.text||'Open in app',url}]]};}return p;}
function notify(text,opts){const ids=Object.keys(load().chats||{});if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyApprovers(nature,text,opts){const s=load(),wanted=String(nature||'SANKI').toUpperCase(),ids=Object.keys(s.chats||{}).filter(id=>{const target=userSummary(s.chats[id]&&s.chats[id].name),r=target&&target.roles||[];if(r.includes('admin')||r.includes('owner'))return true;if(wanted==='SAMAST')return r.includes('samast_accounting');return r.includes('accounting');});if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyUser(username,text,opts){const id=load().userChats[String(username||'').toLowerCase()];if(!configured()||!id)return Promise.resolve({sent:0});return tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))).then(r=>({sent:r&&r.ok?1:0})).catch(()=>({sent:0}));}
router.post('/api/telegram/webhook/:secret',express.json(),(req,res)=>{const s=load(),header=req.get('x-telegram-bot-api-secret-token')||'';if(!s.webhookSecret||(req.params.secret!==s.webhookSecret&&header!==s.webhookSecret))return res.status(403).end();const msg=(req.body||{}).message||(req.body||{}).edited_message;if(msg&&msg.chat){s.updates++;const id=String(msg.chat.id),raw=String(msg.text||'').trim(),m=raw.match(/^\/start(?:@\w+)?\s+([a-f0-9]{32})$/i),link=m&&s.linkCodes[m[1]];if(link&&Date.now()<link.expiresAt){s.userChats[String(link.username).toLowerCase()]=id;if(link.approver)s.chats[id]={id,name:link.username,at:new Date().toISOString()};delete s.linkCodes[m[1]];save(s);tg('sendMessage',{chat_id:id,text:'✅ Telegram linked to your SANKI account. Expense updates will arrive here.'});}else if(/^\/stop\b/i.test(raw)){delete s.chats[id];Object.keys(s.userChats).forEach(u=>{if(s.userChats[u]===id)delete s.userChats[u];});save(s);tg('sendMessage',{chat_id:id,text:'🔕 SANKI notifications disconnected.'});}else{save(s);tg('sendMessage',{chat_id:id,text:'Ask the Owner for a fresh SANKI Telegram linking link.'});}}res.json({ok:true});});
router.post('/api/telegram/link',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});if(!configured())return res.json({success:true,configured:false,username:target.username,url:'',expiresInMinutes:15});const finish=botUsername=>{if(!botUsername)return res.json({success:false,configured:true,error:'Could not identify the configured Telegram bot.'});const s=load(),code=crypto.randomBytes(16).toString('hex');s.botUsername=botUsername;s.linkCodes[code]={username:target.username,approver:target.roles.some(r=>['admin','owner','accounting','samast_accounting'].includes(r)),expiresAt:Date.now()+900000};Object.keys(s.linkCodes).forEach(k=>{if(s.linkCodes[k].expiresAt<Date.now())delete s.linkCodes[k];});save(s);res.json({success:true,configured:true,username:target.username,url:'https://t.me/'+botUsername+'?start='+code,expiresInMinutes:15});};const known=load().botUsername;if(known)return finish(known);tg('getMe',{}).then(me=>finish(me&&me.ok?me.result.username:''));});
router.get('/api/telegram/status',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const s=load(),localUrl=base()+'/api/telegram/webhook/';if(!configured())return res.json({success:true,configured:false,webhookSet:false,connectedToThisApp:false,subscribers:Object.keys(s.chats).length,linkedUsers:Object.keys(s.userChats).length,linkedUsernames:Object.keys(s.userChats),botUsername:s.botUsername||''});Promise.all([tg('getMe',{}),tg('getWebhookInfo',{})]).then(([me,hook])=>{const currentUrl=hook&&hook.ok&&hook.result?String(hook.result.url||''):'';res.json({success:true,configured:true,webhookSet:!!currentUrl,connectedToThisApp:currentUrl.startsWith(localUrl),pendingUpdates:hook&&hook.ok&&hook.result?Number(hook.result.pending_update_count||0):null,subscribers:Object.keys(s.chats).length,linkedUsers:Object.keys(s.userChats).length,linkedUsernames:Object.keys(s.userChats),botUsername:me&&me.ok?me.result.username:(s.botUsername||'')});}).catch(()=>res.status(502).json({success:false,error:'Could not inspect the Telegram bot.'}));});
router.post('/api/telegram/setup',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});if(!configured())return res.json({success:false,error:'TELEGRAM_BOT_TOKEN is not configured on Railway.'});const s=load();if(!s.webhookSecret)s.webhookSecret=crypto.randomBytes(24).toString('hex');Promise.all([tg('getMe',{}),tg('setWebhook',{url:base()+'/api/telegram/webhook/'+s.webhookSecret,secret_token:s.webhookSecret,allowed_updates:['message']})]).then(([me,hook])=>{if(me&&me.ok)s.botUsername=me.result.username;save(s);res.json(hook&&hook.ok?{success:true,botUsername:s.botUsername}:{success:false,error:(hook&&hook.description)||'Webhook setup failed.'});});});
router.post('/api/telegram/test',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const username=String(req.body&&req.body.username||'').trim();if(username){const target=userSummary(username);if(!target)return res.status(404).json({success:false,error:'User not found.'});return notifyUser(target.username,'🔔 <b>Your SANKI Telegram notifications are working.</b>').then(r=>res.json(r.sent?{success:true,sent:r.sent,username:target.username}:{success:false,sent:0,error:'This user has not linked Telegram yet.'}));}notify('🔔 <b>SANKI Telegram notifications are working.</b>').then(r=>res.json({success:true,sent:r.sent}));});
router.post('/api/telegram/unlink',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});const s=load(),key=target.username.toLowerCase(),chatId=s.userChats[key];delete s.userChats[key];if(chatId&&!Object.values(s.userChats).includes(chatId))delete s.chats[chatId];save(s);res.json({success:true,username:target.username,wasLinked:!!chatId});});
module.exports={router,notify,notifyApprovers,notifyUser,esc,configured};
