const express=require('express'),https=require('https'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{userSummary}=require('./auth-users');
const {createWorker}=require('tesseract.js'),eng=require('@tesseract.js-data/eng');
const router=express.Router(),DIR=process.env.DATA_PATH?path.dirname(process.env.DATA_PATH):path.join(__dirname,'..'),FILE=path.join(DIR,'telegram.json');
function blank(){return{chats:{},chatMeta:{},userChats:{},linkCodes:{},personalChats:{},personalChatMeta:{},personalUserChats:{},personalLinkCodes:{},pendingCaptures:{},businessDrafts:{},paymentPrompts:{},transferPrompts:{},bankStatementPrompts:{},webhookSecret:'',personalWebhookSecret:'',botUsername:'',personalBotUsername:'',updates:0,personalUpdates:0};}
function load(){try{return Object.assign(blank(),JSON.parse(fs.readFileSync(FILE,'utf8')));}catch{return blank();}}
function save(s){const t=FILE+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(t,JSON.stringify(s));fs.renameSync(t,FILE);}
// Backward compatible: old production data stores one chat id as a scalar;
// new data stores an array so one app user can receive notifications in several
// Telegram accounts without replacing the existing link.
function chatIdsForUser(s,username){const v=(s.userChats||{})[String(username||'').toLowerCase()];return(Array.isArray(v)?v:(v!=null&&v!==''?[v]:[])).map(String).filter((x,i,a)=>a.indexOf(x)===i);}
function personalChatIdsForUser(s,username){const v=(s.personalUserChats||{})[String(username||'').toLowerCase()];return(Array.isArray(v)?v:(v!=null&&v!==''?[v]:[])).map(String).filter((x,i,a)=>a.indexOf(x)===i);}
function allLinkedChatIds(s){return Object.keys(s.userChats||{}).reduce((a,u)=>a.concat(chatIdsForUser(s,u)),[]).filter((x,i,a)=>a.indexOf(x)===i);}
function token(){return String(process.env.TELEGRAM_BOT_TOKEN||'').trim();} function personalToken(){return String(process.env.TELEGRAM_PERSONAL_BOT_TOKEN||'').trim();} function configured(){return!!token();} function personalConfigured(){return!!personalToken();}
function base(){return String(process.env.PUBLIC_URL||(process.env.RAILWAY_PUBLIC_DOMAIN?'https://'+process.env.RAILWAY_PUBLIC_DOMAIN:'')||'https://sanki-ops.up.railway.app').replace(/\/$/,'');}
function esc(v){return String(v==null?'':v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function roles(q){return(q.user&&(q.user.roles||(q.user.role?[q.user.role]:[])))||[];} function owner(q){return roles(q).includes('owner');}
function tgOnceWith(botToken,method,payload){return new Promise(resolve=>{if(!botToken)return resolve({ok:false,description:'Telegram is not configured'});const data=JSON.stringify(payload||{}),q=https.request({hostname:'api.telegram.org',path:'/bot'+botToken+'/'+method,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>{try{resolve(JSON.parse(b));}catch{resolve({ok:false,description:'Invalid response from Telegram'});}});});q.setTimeout(10000,()=>q.destroy(new Error('Telegram request timed out')));q.on('error',e=>resolve({ok:false,description:e&&e.message||'Telegram request failed'}));q.write(data);q.end();});}
function tgWith(botToken,label,method,payload){let attempt=0;const run=()=>tgOnceWith(botToken,method,payload).then(result=>{attempt++;if(result&&result.ok)return result;if(attempt<3)return new Promise(resolve=>setTimeout(resolve,attempt*750)).then(run);console.warn('['+label+'] '+method+' failed after '+attempt+' attempts: '+String(result&&result.description||'unknown error'));return result||{ok:false};});return run();}
function tg(method,payload){return tgWith(token(),'telegram',method,payload);} function tgPersonal(method,payload){return tgWith(personalToken(),'telegram-personal',method,payload);}
function tgPhotoWith(botToken,send,chatId,url,caption,replyMarkup){const fp=path.join(DIR,'expense-proofs',path.basename(String(url||'')));if(!url||!fs.existsSync(fp))return send('sendMessage',{chat_id:chatId,text:caption||'Proof is available in the app.',parse_mode:'HTML',reply_markup:replyMarkup});return new Promise(resolve=>{const boundary='----Sanki'+crypto.randomBytes(8).toString('hex'),parts=[],field=(k,v)=>parts.push(Buffer.from('--'+boundary+'\r\nContent-Disposition: form-data; name="'+k+'"\r\n\r\n'+String(v)+'\r\n'));field('chat_id',chatId);field('caption',caption||'');field('parse_mode','HTML');if(replyMarkup)field('reply_markup',JSON.stringify(replyMarkup));parts.push(Buffer.from('--'+boundary+'\r\nContent-Disposition: form-data; name="photo"; filename="'+path.basename(fp)+'"\r\nContent-Type: image/jpeg\r\n\r\n'));parts.push(fs.readFileSync(fp));parts.push(Buffer.from('\r\n--'+boundary+'--\r\n'));const body=Buffer.concat(parts),q=https.request({hostname:'api.telegram.org',path:'/bot'+botToken+'/sendPhoto',method:'POST',headers:{'Content-Type':'multipart/form-data; boundary='+boundary,'Content-Length':body.length}},r=>{let out='';r.on('data',c=>out+=c);r.on('end',()=>{try{resolve(JSON.parse(out));}catch{resolve({ok:false});}});});q.on('error',()=>resolve({ok:false}));q.write(body);q.end();});}
function tgPhoto(chatId,url,caption,replyMarkup){return tgPhotoWith(token(),tg,chatId,url,caption,replyMarkup);} function tgPersonalPhoto(chatId,url,caption,replyMarkup){return tgPhotoWith(personalToken(),tgPersonal,chatId,url,caption,replyMarkup);}
function ensureWebhookUpdates(){const s=load();let changed=false;const ownerKey='gaganlambasanki',ownerMain=chatIdsForUser(s,ownerKey);if(ownerMain.length){s.personalUserChats[ownerKey]=Array.from(new Set(personalChatIdsForUser(s,ownerKey).concat(ownerMain)));ownerMain.forEach(id=>{if(s.chatMeta[id])s.personalChatMeta[id]=s.chatMeta[id];s.personalChats[id]={id,name:ownerKey,at:new Date().toISOString()};});changed=true;}const namitaMain=chatIdsForUser(s,'namita');if(namitaMain.length){s.personalUserChats.namita=Array.from(new Set(personalChatIdsForUser(s,'namita').concat(namitaMain)));namitaMain.forEach(id=>{if(s.chatMeta[id])s.personalChatMeta[id]=s.chatMeta[id];s.personalChats[id]={id,name:'namita',at:new Date().toISOString()};delete s.chats[id];delete s.chatMeta[id];});delete s.userChats.namita;changed=true;}if(configured()&&s.webhookSecret)tg('setWebhook',{url:base()+'/api/telegram/webhook/'+s.webhookSecret,secret_token:s.webhookSecret,allowed_updates:['message','callback_query']}).catch(()=>{});if(personalConfigured()){if(!s.personalWebhookSecret){s.personalWebhookSecret=crypto.randomBytes(24).toString('hex');changed=true;}const personalUrl=base()+'/api/telegram/personal-webhook/'+s.personalWebhookSecret;tgPersonal('setWebhook',{url:personalUrl,secret_token:s.personalWebhookSecret,allowed_updates:['message','callback_query']}).then(hook=>{if(hook&&hook.ok)console.log('[telegram-personal] webhook connected to '+base());else console.error('[telegram-personal] webhook setup failed:',hook&&hook.description||'unknown error');});tgPersonal('getMe',{}).then(me=>{if(me&&me.ok){const latest=load();latest.personalBotUsername=me.result.username;save(latest);console.log('[telegram-personal] configured bot @'+me.result.username);}else console.error('[telegram-personal] bot token check failed:',me&&me.description||'unknown error');});tgPersonal('getWebhookInfo',{}).then(hook=>{const result=hook&&hook.ok&&hook.result;if(result)console.log('[telegram-personal] webhook status pending='+Number(result.pending_update_count||0)+(result.last_error_message?' error='+result.last_error_message:''));});}if(changed)save(s);}
function payload(text,opts){const p={text,parse_mode:'HTML',disable_web_page_preview:true},b=opts&&opts.button;if(b){const target=b.url||b.path||'',url=/^https?:\/\//.test(target)?target:base()+(target.startsWith('/')?target:'/'+target);p.reply_markup={inline_keyboard:[[{text:b.text||'Open in app',url}]]};}return p;}
function notify(text,opts){const ids=Object.keys(load().chats||{});if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyApprovers(nature,text,opts){const s=load(),wanted=String(nature||'SANKI').toUpperCase(),ids=Object.keys(s.chats||{}).filter(id=>{const target=userSummary(s.chats[id]&&s.chats[id].name),r=target&&target.roles||[];if(wanted==='PERSONAL')return r.includes('owner');if(r.includes('admin')||r.includes('owner'))return true;if(wanted==='SAMAST')return r.includes('samast_accounting');return r.includes('accounting');});if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyUser(username,text,opts){const ids=chatIdsForUser(load(),username);if(!configured()||!ids.length)return Promise.resolve({sent:0});return Promise.all(ids.map(id=>tg('sendMessage',Object.assign({chat_id:id},payload(text,opts))))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function notifyUserWithPhoto(username,url,text,opts){const ids=chatIdsForUser(load(),username);if(!configured()||!ids.length)return Promise.resolve({sent:0});const p=payload(text,opts);return Promise.all(ids.map(id=>tgPhoto(id,url,p.text,p.reply_markup))).then(rs=>({sent:rs.filter(r=>r&&r.ok).length})).catch(()=>({sent:0}));}
function parsePersonalCaption(raw){
  const text=String(raw||'').trim();
  if(!/^\/?personal\b/i.test(text))return{ok:false,error:'Start the narration with Personal.'};
  if(!text.includes('|')){
    let body=text.replace(/^\/?personal\b/i,'').trim(),datePart=(body.match(/\b\d{4}-\d{2}-\d{2}\b/)||[])[0]||'';
    const accountMatch=body.match(/\bcash\b|\b\d{4}\b/i),accountPart=accountMatch?accountMatch[0]:'';
    const marked=body.match(/(?:₹|\brs\.?\b|\binr\b)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/i),numbers=body.match(/\b[0-9][0-9,]*(?:\.\d{1,2})?\b/g)||[];
    const candidates=numbers.filter(x=>x!==accountPart&&!datePart.includes(x)),amountText=marked?marked[1]:(candidates[candidates.length-1]||''),amount=Number(String(amountText).replace(/,/g,''));
    let narration=body;if(datePart)narration=narration.replace(datePart,' ');if(accountPart)narration=narration.replace(accountPart,' ');if(marked)narration=narration.replace(marked[0],' ');else if(amountText)narration=narration.replace(new RegExp('\\b'+amountText.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b'),' ');narration=narration.replace(/[|,;-]+/g,' ').replace(/\s+/g,' ').trim();
    if(!narration)return{ok:false,error:'Add a short purpose or vendor narration.'};if(!accountPart)return{ok:false,error:'Add the account last four digits.'};if(!(amount>0))return{ok:false,error:'Add the payment amount.'};
    return{ok:true,amount,account:accountPart,particulars:narration,date:datePart};
  }
  const parts=text.split('|').map(x=>x.trim()).filter(Boolean);
  const amountPart=parts.find((x,i)=>i>0&&/(?:₹|\brs\.?\b|\binr\b)\s*[0-9]/i.test(x))||parts.find((x,i)=>i>0&&/^\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/.test(x)&&!/^\d{4}$/.test(x)),amountMatch=amountPart&&amountPart.match(/([0-9][0-9,]*(?:\.\d{1,2})?)/),amount=amountMatch?Number(amountMatch[1].replace(/,/g,'')):0;
  const accountPart=parts.find((x,i)=>i>0&&(/\b\d{4}\b/.test(x)||/cash/i.test(x)))||'';
  const datePart=parts.find(x=>/^\d{4}-\d{2}-\d{2}$/.test(x))||'';
  const narration=parts.slice(1).filter(x=>x!==accountPart&&x!==datePart&&x!==amountPart).join(' | ').trim();
  if(!narration)return{ok:false,error:'Add a short purpose or vendor narration.'};
  if(!accountPart)return{ok:false,error:'Add the account name or its last four digits.'};
  if(!(amount>0))return{ok:false,error:'Add the payment amount.'};
  return{ok:true,amount,account:accountPart,particulars:narration,date:datePart};
}
function parsePersonalIntent(raw){
  let text=String(raw||'').trim();if(/^\/?(?:sanki|samast|summer)\b/i.test(text))return{ok:false,error:'Telegram recording is PERSONAL only. Record SANKI and SAMAST activity in the app.'};text=text.replace(/^\/?personal\b/i,'').trim();const received=/\breceived\b/i.test(text),cash=/^cash\b/i.test(text),upi=/\bupi\b/i.test(text),tail=text.match(/(?:₹|\brs\.?\b|\binr\b)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)\s*$/i),amount=tail?Number(tail[1].replace(/,/g,'')):0;
  let particulars=text.replace(/\b(?:cash|upi|received)\b/ig,' ').replace(/(?:₹|\brs\.?\b|\binr\b)\s*[0-9][0-9,]*(?:\.\d{1,2})?/ig,' ').replace(/\b\d{4}-\d{2}-\d{2}\b/g,' ').replace(/\b[0-9][0-9,]*(?:\.\d{1,2})?\b/g,' ').replace(/[|,;-]+/g,' ').replace(/\s+/g,' ').trim();
  return particulars?{ok:true,particulars,received,cash,upi,amount}:{ok:false,error:'Add a short purpose or vendor narration.'};
}
function parsePaymentOcr(raw){
  const text=String(raw||''),clean=text.replace(/\r/g,''),lines=clean.split('\n').map(x=>x.trim()).filter(Boolean),pi=lines.findIndex(x=>/paid\s+to/i.test(x)),paidBlock=pi>=0?[lines[pi],lines[pi+1]||'',lines[pi+2]||''].join(' '):'';
  const currencyValues=s=>Array.from(String(s||'').matchAll(/(?:₹|\brs\.?\b|\binr\b)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/ig)).map(m=>Number(m[1].replace(/,/g,''))).filter(n=>n>0&&n<10000000),blockValues=currencyValues(paidBlock),allValues=currencyValues(clean),counts={};allValues.forEach(n=>counts[n]=(counts[n]||0)+1);const repeated=Object.keys(counts).map(Number).filter(n=>counts[n]>1).sort((a,b)=>counts[b]-counts[a]),amount=blockValues[0]||repeated[0]||allValues[0]||0,distinctAmounts=Array.from(new Set(allValues)),explicitAmount=currencyValues((clean.match(/(?:amount|total paid|transaction amount)[^\n]*/i)||[])[0]||'')[0]||0,amountConfidence=!!amount&&(counts[amount]>1||explicitAmount===amount)&&(distinctAmounts.length<=1||counts[amount]>1);
  const debited=(clean.match(/debited\s+from[\s\S]{0,120}?(?:x+|\*+|•+)?\s*(\d{2,4})\b/i)||clean.match(/(?:x{2,}|\*{2,}|•{2,})\s*(\d{2,4})\b/i)||[])[1]||'';
  let recipient='';if(pi>=0){recipient=lines[pi].replace(/^.*?paid\s+to\s*/i,'').replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').trim();if(!recipient&&lines[pi+1])recipient=lines[pi+1].replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').replace(/^[^A-Za-z]+/,'').trim();}
  const months={january:'01',february:'02',march:'03',april:'04',may:'05',june:'06',july:'07',august:'08',september:'09',october:'10',november:'11',december:'12'},dm=clean.match(/\b(\d{1,2})\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(20\d{2})\b/i),date=dm?dm[3]+'-'+months[dm[2].toLowerCase()]+'-'+String(dm[1]).padStart(2,'0'):'';
  return{amount,account:debited,recipient,date,text:clean,distinctAmounts,amountConfidence};
}
function parseReceiptOcr(raw){
  const base=parsePaymentOcr(raw),text=String(raw||'').replace(/\r/g,''),lines=text.split('\n').map(x=>x.trim()).filter(Boolean),ri=lines.findIndex(x=>/received\s+from/i.test(x)),receivedLine=ri>=0?[lines[ri].replace(/^.*?received\s+from\s*/i,''),lines[ri+1]||''].join(' '):'',amountText=(receivedLine.match(/(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)\s*$/i)||text.match(/(?:₹|rs\.?|inr)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/i)||[])[1]||'',credited=(text.match(/credited\s+(?:to|in)[\s\S]{0,120}?(?:x+|\*+|•+)?\s*(\d{2,4})\b/i)||text.match(/(?:x{2,}|\*{2,}|•{2,})\s*(\d{2,4})\b/i)||[])[1]||'';let source='';if(ri>=0){source=lines[ri].replace(/^.*?received\s+from\s*/i,'').replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').trim();if(!source&&lines[ri+1])source=lines[ri+1].replace(/(?:₹|rs\.?|inr)?\s*[0-9][0-9,]*(?:\.\d{1,2})?\s*$/i,'').replace(/^[^A-Za-z]+/,'').trim();}
  return{amount:Number(amountText.replace(/,/g,''))||base.amount,account:credited,source,date:base.date,text};
}
function inferPersonalCategory(narration,recipient){
  const t=(String(narration||'')+' '+String(recipient||'')).toLowerCase(),rules=[
    ['Food & Dining',/food|dining|restaurant|cafe|coffee|grocery|meal|lunch|dinner|breakfast|tip\b/],['Household Staff',/nanny|maid|driver|cook|helper|domestic|house staff|salary/],['Children & Education',/school|tuition|education|book|child|kid|uniform/],['Medical & Healthcare',/doctor|hospital|medicine|medical|pharmacy|clinic|health/],['Travel & Transport',/uber|ola|rapido|fuel|petrol|diesel|travel|flight|train|taxi|parking/],['Home & Utilities',/electricity|water|rent|repair|plumber|carpenter|home|utility|internet|broadband/],['Shopping',/amazon|myntra|clothes|shopping|purchase/],['Subscriptions',/subscription|netflix|spotify|software|membership/],['Personal Care',/salon|gym|spa|personal care|beauty/],['Gifts & Charity',/gift|donation|charity/],['Entertainment',/movie|cinema|game|entertainment/],['Financial Charges',/bank charge|fee|interest|penalty/]
  ];for(const r of rules)if(r[1].test(t))return{ledger:r[0],confidence:true};return{ledger:'Miscellaneous Personal',confidence:false};
}
let workerPromise;function ocrWorker(){if(!workerPromise)workerPromise=createWorker(eng.code,1,{langPath:eng.langPath,gzip:eng.gzip,cacheMethod:'none'});return workerPromise;}
async function readPaymentScreenshot(filePath){const worker=await ocrWorker(),result=await worker.recognize(filePath);return parsePaymentOcr(result&&result.data&&result.data.text||'');}
function downloadPhoto(fileId,prefix,targetDir,botTokenOverride){const activeToken=botTokenOverride||token(),send=botTokenOverride?tgPersonal:tg;
  return send('getFile',{file_id:fileId}).then(info=>new Promise((resolve,reject)=>{
    const remote=info&&info.ok&&info.result&&info.result.file_path;if(!remote)return reject(new Error('Telegram could not provide the image.'));
    const ext=(path.extname(remote)||'.jpg').toLowerCase().replace(/[^.a-z0-9]/g,'')||'.jpg',dir=targetDir||path.join(DIR,'expense-proofs');try{fs.mkdirSync(dir,{recursive:true});}catch{}
    const name=(prefix||'personal-tg')+'-'+Date.now()+'-'+crypto.randomBytes(6).toString('hex')+ext,fp=path.join(dir,name);
    https.get({hostname:'api.telegram.org',path:'/file/bot'+activeToken+'/'+remote},r=>{const chunks=[];let size=0;r.on('data',c=>{size+=c.length;if(size>15*1024*1024)r.destroy(new Error('Image is too large.'));else chunks.push(c);});r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)return reject(new Error('Telegram image download failed.'));fs.writeFileSync(fp,Buffer.concat(chunks));resolve({url:'/api/expenses/photo/'+name,filePath:fp});});r.on('error',reject);}).on('error',reject);
  }));
}
function linkedUsername(s,chatId){return Object.keys(s.userChats||{}).find(u=>chatIdsForUser(s,u).includes(String(chatId)))||'';}
function linkedPersonalUsername(s,chatId){return Object.keys(s.personalUserChats||{}).find(u=>personalChatIdsForUser(s,u).includes(String(chatId)))||'';}
function reply(chatId,text,personal){return(personal?tgPersonal:tg)('sendMessage',{chat_id:chatId,text});}
function money(n){const v=Number(n)||0;return '₹'+v.toLocaleString('en-IN',{minimumFractionDigits:Number.isInteger(v)?0:1,maximumFractionDigits:2});}
function accountsMenu(target){const r=target&&target.roles||[],owner=r.includes('owner');if(!owner)return{inline_keyboard:[[{text:'🧾 Pay expense / vendor',callback_data:'am:pay'}],[{text:'🤝 Pay Claim / Reimbursement',callback_data:'am:reimburse'}]]};return{inline_keyboard:[[{text:'🔄 Transfer',callback_data:'am:transfer'},{text:'💰 Money received',callback_data:'am:received'}],[{text:'🧾 Pay expense / vendor',callback_data:'am:pay'},{text:'🤝 Pay Claim / Reimbursement',callback_data:'am:reimburse'}],[{text:'… More',callback_data:'am:more'}]]};}
function sendAccountsMenu(chatId,target){const r=target&&target.roles||[],allowed=r.some(x=>['owner','admin'].includes(x));if(!allowed)return reply(chatId,'Only the Owner or Admin can operate the Accounts menu.');return tg('sendMessage',{chat_id:chatId,text:'<b>SANKIFIER Accounts</b>\n\nChoose what you want to record. Existing expense approvals and payment messages will continue working exactly as before.',parse_mode:'HTML',reply_markup:accountsMenu(target)});}
function sendMoreMenu(chatId){return tg('sendMessage',{chat_id:chatId,text:'<b>More — existing accounting functions</b>\n\nOnly functions already supported by the app are shown here.',parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'🏦 Bank reconciliation',callback_data:'am:bank'}],[{text:'⚖️ Account adjustment',callback_data:'am:adjustment'},{text:'💵 Receivable collection',callback_data:'am:collection'}],[{text:'🧾 Partial vendor payment',callback_data:'am:partial'},{text:'🗂 Consolidated bill payment',callback_data:'am:consolidated'}],[{text:'📦 Procurement payable',callback_data:'am:procurement'}],[{text:'⬅️ Back',callback_data:'am:home'}]]}});}
function accountsActionMessage(action){const messages={
  transfer:'<b>Transfer between accounts</b>\n\nUse Account ledgers → Transfer between accounts on the mobile app. It records one linked debit and credit with the same transfer reference.',
  received:'<b>Money received</b>\n\nUse Account ledgers → Record money received on the mobile app. Existing receipt types, account permissions and proof rules are preserved.',
  pay:'<b>Pay expense / vendor</b>\n\nAttach the payment screenshot. I will read it, ask you to select your paying account and category, and show a review before anything is recorded.',
  reimburse:'<b>Pay Claim / Reimbursement</b>\n\nOpen Reimbursements, select the claimant expense, one of your assigned paying accounts and proof. Only an existing approved reimbursement can be settled.',
  adjustment:'<b>Account adjustment</b>\n\nUse Account ledgers → Adjustment. The existing reason, date and audit-log rules remain mandatory.',
  collection:'<b>Receivable collection</b>\n\nOpen Receivables and collect against an existing receivable. The receiving account and proof remain mandatory.',
  partial:'<b>Partial vendor payment</b>\n\nOpen Payables, choose the partially paid item and record the next payment against the same expense.',
  consolidated:'<b>Consolidated bill payment</b>\n\nOpen Payables and select multiple outstanding bills for the same vendor. One payment is allocated across the selected bills.',
  procurement:'<b>Procurement payable</b>\n\nOpen Vendor ledgers → Sourcing vendors. This uses the existing Advanced Purchases payable connection.'
};return messages[action]||'';}
function accountsActionButton(action){const tabs={transfer:'accounts',received:'accounts',pay:'payables',reimburse:'reimbursements',adjustment:'accounts',collection:'receivables',partial:'payables',consolidated:'payables',procurement:'vendors'};const tab=tabs[action]||'all';return{inline_keyboard:[[{text:'Open on mobile',url:base()+'/expenses.html?tab='+encodeURIComponent(tab)}],[{text:'⬅️ Accounts menu',callback_data:'am:home'}]]};}
const NATIVE_ACCOUNT_ACTIONS=['received','reimburse','adjustment','collection','partial','consolidated','procurement'];
function nativeActionHelp(action){return{
  received:'Send: SANKI 3645 5000 Customer refund',
  pay:'Send: EX-00052 3645 720',
  reimburse:'Send: EX-00052 3645 720',
  adjustment:'Send: SANKI 3645 add 500 Balance correction',
  collection:'Send: RCV-00001 3448 500',
  partial:'Send: EX-00012 3645 2000',
  consolidated:'Send: EX-00012,EX-00013 | 3645 | 5000',
  procurement:'Send: PO-00012 3645 5000'
}[action]||'';}
function parseNativeAction(action,raw){const t=String(raw||'').trim();let m,d={action,date:new Date().toISOString().slice(0,10)};
  if(action==='received'&&(m=t.match(/^(SANKI|SAMAST|PERSONAL)\s+(\d{4}|cash)\s+([0-9,]+(?:\.\d{1,2})?)\s+(.+)$/i)))Object.assign(d,{nature:m[1].toUpperCase(),account:m[2],amount:Number(m[3].replace(/,/g,'')),source:m[4],note:m[4],receiptType:'other_income'});
  else if(action==='adjustment'&&(m=t.match(/^(SANKI|SAMAST|PERSONAL)\s+(\d{4}|cash)\s+(add|deduct)\s+([0-9,]+(?:\.\d{1,2})?)\s+(.+)$/i)))Object.assign(d,{nature:m[1].toUpperCase(),account:m[2],direction:m[3].toLowerCase(),amount:Number(m[4].replace(/,/g,'')),note:m[5]});
  else if(['pay','reimburse','partial'].includes(action)&&(m=t.match(/^(EX-\d+)\s+(\d{4}|cash)\s+([0-9,]+(?:\.\d{1,2})?)$/i)))Object.assign(d,{id:m[1].toUpperCase(),account:m[2],amount:Number(m[3].replace(/,/g,''))});
  else if(action==='collection'&&(m=t.match(/^(RCV-\d+)\s+(\d{4}|cash)\s+([0-9,]+(?:\.\d{1,2})?)$/i)))Object.assign(d,{id:m[1].toUpperCase(),account:m[2],amount:Number(m[3].replace(/,/g,''))});
  else if(action==='procurement'&&(m=t.match(/^([A-Z]+-[A-Z0-9-]+)\s+(\d{4}|cash)\s+([0-9,]+(?:\.\d{1,2})?)$/i)))Object.assign(d,{id:m[1].toUpperCase(),account:m[2],amount:Number(m[3].replace(/,/g,''))});
  else if(action==='consolidated'){const p=t.split('|').map(x=>x.trim());if(p.length===3&&/^\d{4}$|^cash$/i.test(p[1])&&Number(p[2].replace(/,/g,''))>0)Object.assign(d,{ids:p[0].split(',').map(x=>x.trim().toUpperCase()).filter(x=>/^EX-\d+$/.test(x)),account:p[1],amount:Number(p[2].replace(/,/g,''))});}
  return(d.amount>0&&(d.id||d.ids&&d.ids.length||d.nature))?d:null;}
function nativeActionPreview(d){return'<b>Confirm '+esc(d.action.replace(/_/g,' '))+'</b>\n\n'+(d.nature?'Entity: <b>'+esc(d.nature)+'</b>\n':'')+(d.id?'Reference: <b>'+esc(d.id)+'</b>\n':'')+(d.ids?'Bills: <b>'+esc(d.ids.join(', '))+'</b>\n':'')+'Account: <b>'+esc(d.account)+'</b>\nAmount: <b>'+money(d.amount)+'</b>\n'+(d.direction?'Direction: '+esc(d.direction)+'\n':'')+(d.source?'Source: '+esc(d.source)+'\n':'')+(d.note?'Note: '+esc(d.note)+'\n':'')+'Date: '+esc(d.date)+'\n\nNothing is recorded until Confirm.';}
function sendNativeActionPreview(chatId,d){return tg('sendMessage',{chat_id:chatId,text:nativeActionPreview(d),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm',callback_data:'am:native-confirm'},{text:'✏️ Edit',callback_data:'am:native-edit'}],[{text:'❌ Cancel',callback_data:'am:native-cancel'}]]}});}
const PRASHANT_PAYMENT_ACCOUNTS=['Prashant Axis 3645','Prashant Cash','Counter Cash'];
function quickAccountButtons(){return{inline_keyboard:PRASHANT_PAYMENT_ACCOUNTS.map((name,i)=>[{text:name,callback_data:'am:qacct:'+i}]).concat([[{text:'❌ Cancel',callback_data:'am:qcancel'}]])};}
function sendQuickAccountChoice(chatId){return tg('sendMessage',{chat_id:chatId,text:'<b>Select the paying account</b>\n\nDo not type an account number.',parse_mode:'HTML',reply_markup:quickAccountButtons()});}
function pagedCategoryButtons(prefix,page){const categories=require('./expenses').telegramBusinessCategories(),size=10,p=Math.max(0,Math.min(Number(page)||0,Math.ceil(categories.length/size)-1)),start=p*size,rows=[];for(let i=start;i<Math.min(categories.length,start+size);i+=2)rows.push(categories.slice(i,i+2).map((name,j)=>({text:name,callback_data:prefix+'cat:'+(i+j)})));const nav=[];if(p>0)nav.push({text:'◀ Previous',callback_data:prefix+'catpage:'+(p-1)});if(start+size<categories.length)nav.push({text:'Next ▶',callback_data:prefix+'catpage:'+(p+1)});if(nav.length)rows.push(nav);rows.push([{text:'❌ Cancel',callback_data:prefix.startsWith('am:')?'am:qcancel':'ba:cancel'}]);return{inline_keyboard:rows};}
function sendQuickCategoryChoice(chatId,page){return tg('sendMessage',{chat_id:chatId,text:'<b>Select the expense category</b>\n\nPage '+((Number(page)||0)+1)+'. The system could not identify it confidently.',parse_mode:'HTML',reply_markup:pagedCategoryButtons('am:q',page)});}
function quickExpensePreview(d){return'<b>Review paid expense</b>\n\nEntity: <b>'+esc(d.nature||'SANKI')+'</b>\nVendor: <b>'+esc(d.vendor||'—')+'</b>\nParticulars: '+esc(d.particulars||'—')+'\nCategory: <b>'+esc(d.ledger||'Not selected')+'</b>\nAmount: <b>'+money(d.amount)+'</b>\nPaying account: <b>'+esc(d.account||'Not selected')+'</b>\nDate: '+esc(d.date||'—')+'\n\nNothing is recorded until Confirm.';}
function sendQuickExpensePreview(chatId,d){d.phase='review';d.expiresAt=Date.now()+1800000;return tg('sendMessage',{chat_id:chatId,text:quickExpensePreview(d),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm',callback_data:'am:qconfirm'},{text:'✏️ Edit',callback_data:'am:qedit'}],[{text:'❌ Cancel',callback_data:'am:qcancel'}]]}});}
function runNativeAction(target,d){const e=require('./expenses'),common={amount:d.amount,date:d.date,account:d.account,paymentProof:d.proof,proof:d.proof,note:d.note};
  if(d.action==='received')return e.telegramApi('POST','/api/expenses/receipts',target,{body:Object.assign(common,{nature:d.nature,source:d.source,receiptType:d.receiptType})});
  if(d.action==='adjustment')return e.telegramApi('POST','/api/expenses/balances',target,{body:{nature:d.nature,adjust:{account:d.account,amount:d.amount,direction:d.direction,note:d.note,date:d.date,proof:d.proof}}});
  if(d.action==='reimburse')return e.telegramApi('POST','/api/expenses/:id/reimburse',target,{params:{id:d.id},body:common});
  if(d.action==='collection')return e.telegramApi('POST','/api/expenses/receivables/:id/receive',target,{params:{id:d.id},body:common});
  if(d.action==='procurement')return e.telegramApi('POST','/api/expenses/procurement-payables/:id/pay',target,{params:{id:d.id},body:common});
  if(d.action==='consolidated')return e.telegramApi('POST','/api/expenses/batch-pay',target,{body:Object.assign(common,{expenseIds:d.ids})});
  return e.telegramApi('POST','/api/expenses/:id/pay',target,{params:{id:d.id},body:common});}
function capturePreview(p){const x=p.payload||{},kind=p.kind==='receipt'?'money received':'expense';return '<b>Please confirm this PERSONAL '+kind+'</b>\n\n'+(p.kind==='receipt'?'<b>Source:</b> '+esc(x.source||'—'):'<b>Particulars:</b> '+esc(x.particulars||'—')+'\n<b>Paid to:</b> '+esc(x.vendor||'—')+'\n<b>Category:</b> '+esc(x.ledger||'—'))+'\n<b>Account:</b> '+esc(x.account||'—')+'\n<b>Amount:</b> '+money(x.amount)+'\n<b>Date:</b> '+esc(x.date||new Date().toISOString().slice(0,10))+'\n\nNothing is recorded until you press Confirm.';}
function sendCapturePreview(chatId,p,personal){p.phase='review';p.expiresAt=Date.now()+1800000;return(personal?tgPersonal:tg)('sendMessage',{chat_id:chatId,text:capturePreview(p),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm',callback_data:'personal_confirm'},{text:'✏️ Edit',callback_data:'personal_edit'}],[{text:'❌ Cancel',callback_data:'personal_cancel'}]]}});}
function applyCaptureEdit(p,raw){const text=String(raw||'').trim(),x=p.payload||{};let m;if((m=text.match(/^amount\s*[:=-]?\s*(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)$/i))){x.amount=Number(m[1].replace(/,/g,''));return x.amount>0;}if((m=text.match(/^account\s*[:=-]?\s*(cash|[0-9]{2,4})$/i))){x.account=m[1];return true;}if((m=text.match(/^(?:particulars?|purpose|narration)\s*[:=-]?\s*(.+)$/i))){x.particulars=m[1].trim();if(p.kind==='receipt')x.source=x.particulars;else{const c=inferPersonalCategory(x.particulars,x.vendor);x.ledger=c.ledger;}return!!x.particulars;}if((m=text.match(/^category\s*[:=-]?\s*(.+)$/i))){x.ledger=m[1].trim();return!!x.ledger;}return false;}
function completePending(p,target){const expenses=require('./expenses');if(p.kind==='receipt'){const result=expenses.createTelegramPersonalReceipt(Object.assign({},p.payload,{username:target.username}));if(!result.success)return{ok:false,text:'Could not record this receipt: '+result.error};const x=result.receipt;return{ok:true,text:'✅ PERSONAL money received recorded\n'+x.id+' · '+money(x.amount)+' · '+x.source+'\nReceived in: '+x.account};}const result=expenses.createTelegramPersonalExpense(Object.assign({},p.payload,{username:target.username}));if(!result.success)return{ok:false,text:'Could not record this expense: '+result.error};const e=result.expense;return{ok:true,text:'✅ PERSONAL expense recorded and marked paid\n'+e.id+' · '+money(e.amount)+' · '+e.particulars+'\nAccount: '+e.account+'\nCategory: '+e.ledger};}
function canApproveBusiness(target,nature){const r=target&&target.roles||[],wanted=String(nature||'SANKI').toUpperCase();if(wanted==='PERSONAL')return r.includes('owner');if(r.includes('owner')||r.includes('admin'))return true;return wanted==='SAMAST'?r.includes('samast_accounting'):r.includes('accounting');}
function approverChatIds(s,nature){return Object.keys(s.chats||{}).filter(id=>canApproveBusiness(userSummary(s.chats[id]&&s.chats[id].name),nature));}
function approvalText(e){const paymentState=e.paidAlready?'✅ <b>Already paid by claimant</b> — approve for reimbursement':'⏳ <b>Not paid yet</b> — approve first, then pay the vendor';return '<b>'+esc(e.nature||'SANKI')+' · '+esc(e.id)+'</b>\nClaimant: <b>'+esc(e.createdBy||e.claimant||'—')+'</b>\nVendor: <b>'+esc(e.vendor||'—')+'</b>\nParticulars: '+esc(e.particulars||'—')+'\nAmount: <b>'+money(e.amount)+'</b>\nPayment status: '+paymentState+'\nCategory: '+esc(e.ledger||'Not assigned')+'\nPayment type: '+esc(e.paymentType||'—');}
function approvalButtons(e){const id=e.id,first=e.ledger?[{text:'✅ Approve',callback_data:'ba:approve:'+id},{text:'✏️ Edit',callback_data:'ba:edit:'+id}]:[{text:'🏷 Select category',callback_data:'ba:categories:'+id},{text:'✏️ Edit',callback_data:'ba:edit:'+id}];return{inline_keyboard:[first,[{text:'❌ Reject',callback_data:'ba:reject:'+id},{text:'Open in app',url:base()+'/expenses.html?focus='+encodeURIComponent(id)}]]};}
function approvalCategoryButtons(expenseId,page){const categories=require('./expenses').telegramBusinessCategories(),size=10,p=Math.max(0,Math.min(Number(page)||0,Math.ceil(categories.length/size)-1)),start=p*size,rows=[];for(let i=start;i<Math.min(categories.length,start+size);i+=2)rows.push(categories.slice(i,i+2).map((name,j)=>({text:name,callback_data:'ba:cat:'+expenseId+':'+(i+j)})));const nav=[];if(p>0)nav.push({text:'◀ Previous',callback_data:'ba:catpage:'+expenseId+':'+(p-1)});if(start+size<categories.length)nav.push({text:'Next ▶',callback_data:'ba:catpage:'+expenseId+':'+(p+1)});if(nav.length)rows.push(nav);rows.push([{text:'Cancel',callback_data:'ba:cancel:'+expenseId}]);return{inline_keyboard:rows};}
function notifyExpenseForApproval(e){const s=load(),ids=approverChatIds(s,e.nature),personal=String(e.nature||'').toUpperCase()==='PERSONAL'&&personalConfigured(),photo=personal?tgPersonalPhoto:tgPhoto;return Promise.all(ids.map(id=>photo(id,e.billPhoto,'🧾 <b>New expense awaiting approval</b>\n'+approvalText(e),approvalButtons(e)).then(()=>e.qrPhoto?photo(id,e.qrPhoto,'Vendor QR for <b>'+esc(e.id)+'</b>'):null))).then(()=>({sent:ids.length}));}
function sendPaymentOptions(chatId,e){if(e.paidAlready)return reply(chatId,'✅ '+e.id+' approved. It was already paid personally; reimbursement is now pending.');const buttons={inline_keyboard:[[{text:'💳 Record payment',callback_data:'bp:start:'+e.id},{text:'Pay later',callback_data:'bp:later:'+e.id}],[{text:'Open in app',url:base()+'/expenses.html?focus='+encodeURIComponent(e.id)}]]};return(e.qrPhoto?tgPhoto(chatId,e.qrPhoto,'✅ <b>'+esc(e.id)+' approved</b>\nVendor QR · '+esc(e.vendor)+' · '+money(e.amount),buttons):tg('sendMessage',{chat_id:chatId,text:'✅ <b>'+esc(e.id)+' approved</b>\n'+esc(e.vendor)+' · '+money(e.amount),parse_mode:'HTML',reply_markup:buttons}));}
function sendPersonalPaymentOptions(chatId,e){if(e.paidAlready)return reply(chatId,'✅ '+e.id+' approved. It was already paid personally; reimbursement is now pending.',true);const buttons={inline_keyboard:[[{text:'💳 Record payment',callback_data:'bp:start:'+e.id},{text:'Pay later',callback_data:'bp:later:'+e.id}],[{text:'Open in app',url:base()+'/expenses.html?focus='+encodeURIComponent(e.id)}]]};return(e.qrPhoto?tgPersonalPhoto(chatId,e.qrPhoto,'✅ <b>'+esc(e.id)+' approved</b>\nVendor QR · '+esc(e.vendor)+' · '+money(e.amount),buttons):tgPersonal('sendMessage',{chat_id:chatId,text:'✅ <b>'+esc(e.id)+' approved</b>\n'+esc(e.vendor)+' · '+money(e.amount),parse_mode:'HTML',reply_markup:buttons}));}
function businessEdit(d,raw){const t=String(raw||'').trim();let m;if((m=t.match(/^amount\s*[:=-]?\s*(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)$/i))){d.changes.amount=Number(m[1].replace(/,/g,''));return true;}for(const spec of [['vendor','vendor'],['particulars','particulars?'],['ledger','category'],['nature','entity'],['type','type'],['paymentType','payment type']]){const re=new RegExp('^'+spec[1]+'\\s*[:=-]?\\s*(.+)$','i');if((m=t.match(re))){d.changes[spec[0]]=m[1].trim();return true;}}return false;}
function businessPreview(e,changes){const x=Object.assign({},e,changes||{});return '<b>Review before approval</b>\n'+approvalText(x)+'\n\nConfirm approves only '+esc(e.id)+'.';}
function sendBusinessPreview(chatId,d){const e=require('./expenses').telegramExpense(d.expenseId);return tg('sendMessage',{chat_id:chatId,text:businessPreview(e,d.changes),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Save & approve',callback_data:'ba:confirm:'+d.expenseId},{text:'✏️ Edit more',callback_data:'ba:edit:'+d.expenseId}],[{text:'Cancel',callback_data:'ba:cancel:'+d.expenseId}]]}});}
function sendPersonalApprovalPreview(chatId,d){const e=require('./expenses').telegramExpense(d.expenseId);return tgPersonal('sendMessage',{chat_id:chatId,text:businessPreview(e,d.changes),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Save & approve',callback_data:'ba:confirm:'+d.expenseId},{text:'✏️ Edit more',callback_data:'ba:edit:'+d.expenseId}],[{text:'Cancel',callback_data:'ba:cancel:'+d.expenseId}]]}});}
function paymentPreview(d){return '<b>Confirm payment for '+esc(d.expenseId)+'</b>\nAmount: <b>'+money(d.amount)+'</b>\nAccount: <b>'+esc(d.account||'Not detected')+'</b>\nDate: '+esc(d.date||'—')+'\n\nNothing is recorded until Confirm.';}
function sendPaymentPreview(chatId,key,d){return tg('sendMessage',{chat_id:chatId,text:paymentPreview(d),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm payment',callback_data:'bp:confirm:'+key},{text:'✏️ Edit',callback_data:'bp:edit:'+key}],[{text:'Cancel',callback_data:'bp:cancel:'+key}]]}});}
function sendPersonalPaymentPreview(chatId,key,d){return tgPersonal('sendMessage',{chat_id:chatId,text:paymentPreview(d),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm payment',callback_data:'bp:confirm:'+key},{text:'✏️ Edit',callback_data:'bp:edit:'+key}],[{text:'Cancel',callback_data:'bp:cancel:'+key}]]}});}
async function handleCallback(query,s){if(!query||!query.message||!query.message.chat)return;const id=String(query.message.chat.id),username=linkedUsername(s,id),target=username&&userSummary(username),r=target&&target.roles||[],canBusiness=r.some(x=>['owner','admin','accounting','samast_accounting'].includes(x)),data=String(query.data||'');await tg('answerCallbackQuery',{callback_query_id:query.id});
  if(data.startsWith('personal_')&&personalConfigured())return reply(id,'PERSONAL capture has moved to @'+(s.personalBotUsername||'personal5665_bot')+'.');
  if(data.startsWith('am:q')){const d=s.accountPrompts&&s.accountPrompts[id];if(!d||d.action!=='quick-paid-expense'||d.expiresAt<Date.now())return reply(id,'This paid-expense draft expired. Start Pay expense / vendor again.');if(data==='am:qcancel'){delete s.accountPrompts[id];save(s);return reply(id,'Expense draft cancelled. Nothing was recorded.');}if(data==='am:qedit'){d.phase='edit';save(s);return reply(id,'Reply with one correction at a time:\nAmount 500\nVendor Vendor name\nParticulars Petrol\nEntity SANKI\n\nUse the account and category buttons to change those fields.');}if(data.startsWith('am:qacct:')){const index=Number(data.split(':')[2]);if(!PRASHANT_PAYMENT_ACCOUNTS[index])return reply(id,'That paying account is not available.');d.account=PRASHANT_PAYMENT_ACCOUNTS[index];d.expiresAt=Date.now()+1800000;save(s);return d.ledger?sendQuickExpensePreview(id,d):sendQuickCategoryChoice(id);}if(data.startsWith('am:qcatpage:'))return sendQuickCategoryChoice(id,Number(data.split(':')[2]));if(data.startsWith('am:qcat:')){const categories=require('./expenses').telegramBusinessCategories(),index=Number(data.split(':')[2]);if(!categories[index])return reply(id,'That category is not available.');d.ledger=categories[index];d.expiresAt=Date.now()+1800000;save(s);return d.account?sendQuickExpensePreview(id,d):sendQuickAccountChoice(id);}if(data==='am:qconfirm'){if(d.phase!=='review')return reply(id,'Complete the missing selections first.');const out=require('./expenses').createTelegramBusinessPaidExpense(Object.assign({},d,{username:target.username}));if(!out.success){if(out.needsCategory)return sendQuickCategoryChoice(id);return reply(id,out.error);}delete s.accountPrompts[id];save(s);return reply(id,'✅ Paid expense recorded\n'+out.expense.id+' · '+money(out.expense.amount)+'\n'+out.expense.vendor+' · '+out.expense.account+'\nCategory: '+out.expense.ledger);}}
  if(data==='am:transfer-cancel'&&!(s.transferPrompts&&s.transferPrompts[id]))return reply(id,'This transfer was already confirmed or the draft expired. Cancel cannot delete a recorded transfer. Use the Owner account ledger to delete it with a reason.');
  if(data==='am:transfer-confirm'&&s.transferPrompts&&s.transferPrompts[id]&&(/5464|namita cash/i.test(String(s.transferPrompts[id].toAccount||'')))){const d=s.transferPrompts[id];if(d.phase!=='review'||d.expiresAt<Date.now())return reply(id,'This transfer draft expired. Start Transfer again.');const out=require('./expenses').telegramRecordNamitaTransfer(target.username,d);if(!out.success)return reply(id,out.error);delete s.transferPrompts[id];save(s);return reply(id,'✅ '+out.transfer.id+' recorded\n'+out.transfer.fromAccount+' → '+out.transfer.toAccount+'\n'+money(out.transfer.amount)+' · '+out.transfer.date);}
  if(data.startsWith('am:')&&!r.includes('owner')&&['am:transfer','am:transfer-edit','am:transfer-confirm','am:transfer-cancel','am:received','am:more','am:bank','am:adjustment','am:collection'].includes(data))return reply(id,'Only the Owner can use this accounting action.');
  if(data==='am:native-cancel'){delete(s.accountPrompts||{})[id];save(s);return reply(id,'Accounting draft cancelled. Nothing was recorded.');}
  if(data==='am:native-edit'){const d=s.accountPrompts&&s.accountPrompts[id];if(!d)return reply(id,'This accounting draft expired.');d.phase='details';save(s);return reply(id,nativeActionHelp(d.action)+'\n\nYour uploaded proof will remain attached.');}
  if(data==='am:native-confirm'){const d=s.accountPrompts&&s.accountPrompts[id];if(!d||d.phase!=='review')return reply(id,'This accounting draft expired.');const out=runNativeAction(target,d);if(!out.success)return reply(id,out.error||'Could not record this accounting action.');delete s.accountPrompts[id];save(s);return reply(id,'✅ Recorded successfully'+(out.receipt?' · '+out.receipt.id:out.transfer?' · '+out.transfer.id:out.expense?' · '+out.expense.id:out.receivable?' · '+out.receivable.id:out.payable?' · '+out.payable.id:''));}
  if(data==='am:pay'){s.accountPrompts=s.accountPrompts||{};s.accountPrompts[id]={action:'quick-paid-expense',phase:'proof',nature:'SANKI',expiresAt:Date.now()+1800000};save(s);return reply(id,'Attach the payment screenshot now. I will read it and then ask you to select the paying account and category. Nothing will be recorded until you confirm.');}
  if(data.startsWith('am:')&&NATIVE_ACCOUNT_ACTIONS.includes(data.slice(3))){const action=data.slice(3);s.accountPrompts=s.accountPrompts||{};s.accountPrompts[id]={action,phase:'details',expiresAt:Date.now()+1800000};save(s);return reply(id,nativeActionHelp(action)+'\n\nAfter this, attach the payment/proof screenshot.');}
  if(data.startsWith('am:')){if(!r.some(x=>['owner','admin'].includes(x)))return reply(id,'Only the Owner or Admin can operate the Accounts menu.');const action=data.slice(3);if(action==='home')return sendAccountsMenu(id,target);if(action==='more')return sendMoreMenu(id);if(action==='transfer'){s.transferPrompts[id]={phase:'details',expiresAt:Date.now()+1800000};save(s);return reply(id,'Send the transfer in one line:\n\n3448 to 3645 5000 Office funds\n\nThat means: FROM account → TO account → amount → short note. I will ask for the transfer screenshot next.');}if(action==='transfer-edit'){const d=s.transferPrompts[id];if(!d||d.expiresAt<Date.now())return reply(id,'This transfer draft expired. Start Transfer again.');d.phase='edit';save(s);return reply(id,'Send the corrected line:\n3448 to 3645 5000 Office funds\n\nYour uploaded proof will remain attached.');}if(action==='transfer-cancel'){delete s.transferPrompts[id];save(s);return reply(id,'Transfer cancelled. Nothing was recorded.');}if(action==='transfer-confirm'){const d=s.transferPrompts[id];if(!d||d.phase!=='review'||d.expiresAt<Date.now())return reply(id,'This transfer draft expired. Start Transfer again.');const out=require('./expenses').telegramRecordTransfer(target.username,d);if(!out.success)return reply(id,out.error);delete s.transferPrompts[id];save(s);return reply(id,'✅ '+out.transfer.id+' recorded\n'+out.transfer.fromAccount+' → '+out.transfer.toAccount+'\n'+money(out.transfer.amount)+' · '+out.transfer.date);}if(action==='bank'){s.bankStatementPrompts[id]={expiresAt:Date.now()+1800000};save(s);return reply(id,'Upload the bank statement here as XLS, XLSX, CSV, PDF or a clear image.\n\nCaption it with the entity and account last four digits, for example:\nSANKI 3645\nSAMAST 7883\n\nI will import and reconcile it, then report differences. Unmatched entries will not be automatically posted.');}const message=accountsActionMessage(action);if(!message)return reply(id,'That accounting option is not available.');return tg('sendMessage',{chat_id:id,text:message,parse_mode:'HTML',reply_markup:accountsActionButton(action)});}
  if(data.startsWith('ba:')){const parts=data.split(':'),action=parts[1],expenseId=parts[2],expenses=require('./expenses'),e=expenses.telegramExpense(expenseId);if(!e)return reply(id,'Expense '+expenseId+' was not found.');if(!canApproveBusiness(target,e.nature))return reply(id,'You are not authorized to approve this expense.');if(action==='categories'||action==='catpage'){s.businessDrafts[id]=s.businessDrafts[id]&&s.businessDrafts[id].expenseId===expenseId?s.businessDrafts[id]:{kind:'approval',expenseId,changes:{},expiresAt:Date.now()+1800000};s.businessDrafts[id].expiresAt=Date.now()+1800000;save(s);const page=action==='catpage'?Number(parts[3]):0;return tg('sendMessage',{chat_id:id,text:'<b>Select a category before approval</b>\nPage '+(page+1),parse_mode:'HTML',reply_markup:approvalCategoryButtons(expenseId,page)});}if(action==='cat'){const index=Number(parts[3]),categories=expenses.telegramBusinessCategories(),category=categories[index];if(!category)return reply(id,'That category is not available.');const draft=s.businessDrafts[id]&&s.businessDrafts[id].expenseId===expenseId?s.businessDrafts[id]:{kind:'approval',expenseId,changes:{},expiresAt:Date.now()+1800000};draft.changes.ledger=category;draft.expiresAt=Date.now()+1800000;s.businessDrafts[id]=draft;save(s);return sendBusinessPreview(id,draft);}if(action==='reject'){const out=expenses.telegramRejectExpense(expenseId,target.username);return reply(id,out.success?'❌ '+expenseId+' rejected.':out.error);}if(action==='cancel'){delete s.businessDrafts[id];save(s);return reply(id,'Approval edit cancelled. Nothing changed.');}if(action==='edit'){const current=s.businessDrafts[id];s.businessDrafts[id]=current&&current.expenseId===expenseId?current:{kind:'approval',expenseId,changes:{},expiresAt:Date.now()+1800000};s.businessDrafts[id].expiresAt=Date.now()+1800000;save(s);return reply(id,'Reply with one correction at a time:\nCategory Fuel Expenses\nAmount 500\nVendor Vendor name\nParticulars Petrol\nEntity SANKI\nType variable\nPayment type UPI');}if(action==='approve'||action==='confirm'){const draft=s.businessDrafts[id]&&s.businessDrafts[id].expenseId===expenseId?s.businessDrafts[id]:{changes:{}};const out=expenses.telegramApproveExpense(expenseId,target.username,draft.changes);if(!out.success){if(out.needsCategory){s.businessDrafts[id]={kind:'approval',expenseId,changes:{},expiresAt:Date.now()+1800000};save(s);return reply(id,'Category is required. Use Select category on the approval message.');}return reply(id,out.error);}delete s.businessDrafts[id];save(s);return sendPaymentOptions(id,out.expense);}}
  if(data.startsWith('bp:')){if(!canBusiness)return reply(id,'You are not authorized to record payments.');const parts=data.split(':'),action=parts[1],key=parts[2],expenses=require('./expenses');if(action==='later')return reply(id,'Payment left pending. Only this expense remains unpaid.');if(action==='start'){const e=expenses.telegramExpense(key);if(!e)return reply(id,'Expense '+key+' was not found.');if(!canApproveBusiness(target,e.nature))return reply(id,'You are not authorized to record this payment.');const due=Math.max(0,Number(e.amount||0)-Number(e.paidAmount||0));if(e.status==='paid'||due<=0)return reply(id,'✅ '+key+' is already fully paid. No second payment can be recorded.');if(!['approved','partially_paid'].includes(e.status)||e.paidAlready)return reply(id,key+' is not awaiting a vendor payment.');const sent=await tg('sendMessage',{chat_id:id,text:'Reply directly to this message with the payment screenshot for '+key+'.\n\nScreenshots sent elsewhere will not be attached.'});if(sent&&sent.ok){s.paymentPrompts[id+':'+sent.result.message_id]=key;save(s);}return;}const draft=s.businessDrafts[key];if(!draft||draft.expiresAt<Date.now())return reply(id,'This payment draft expired. Start Record payment again.');if(action==='cancel'){delete s.businessDrafts[key];save(s);return reply(id,'Payment draft cancelled. Nothing was recorded.');}if(action==='edit'){draft.phase='payment-edit';draft.chatId=id;save(s);return reply(id,'Reply with one correction:\nAmount 500\nAccount 3645');}if(action==='confirm'){const out=expenses.telegramRecordPayment(draft.expenseId,target.username,draft);if(!out.success)return reply(id,out.error);delete s.businessDrafts[key];save(s);return reply(id,'✅ Payment recorded for '+draft.expenseId+'\n'+money(out.payment.amount)+' from '+out.payment.account+'\nStatus: '+out.expense.status);}}
  const p=s.pendingCaptures&&s.pendingCaptures[id],isOwner=r.includes('owner');if(!isOwner||!p||p.expiresAt<Date.now())return reply(id,'This PERSONAL draft has expired. Please send the screenshot again.');if(data==='personal_cancel'){delete s.pendingCaptures[id];save(s);return reply(id,'❌ Draft cancelled. Nothing was recorded.');}if(data==='personal_edit'){p.phase='edit';save(s);return reply(id,'Reply with one correction at a time:\nAmount 5000\nAccount 0993\nParticulars Food restaurant\nCategory Food & Dining\n\nI will show the revised confirmation again.');}if(data==='personal_confirm'){const done=completePending(p,target);if(done.ok)delete s.pendingCaptures[id];save(s);return reply(id,done.text);}}
async function handleWebhookMessage(msg,s){
  if(!msg||!msg.chat)return;const id=String(msg.chat.id),raw=String(msg.caption||msg.text||'').trim(),m=raw.match(/^\/start(?:@\w+)?\s+([a-f0-9]{32})$/i),link=m&&s.linkCodes[m[1]];
  if(link&&Date.now()<link.expiresAt){const key=String(link.username).toLowerCase(),ids=chatIdsForUser(s,key);if(!ids.includes(String(id)))ids.push(String(id));s.userChats[key]=ids;s.chatMeta=s.chatMeta||{};s.chatMeta[id]={id,name:link.username,telegramName:String(msg.chat.username?('@'+msg.chat.username):([msg.chat.first_name,msg.chat.last_name].filter(Boolean).join(' ')||'Telegram account')),at:new Date().toISOString()};if(link.approver)s.chats[id]={id,name:link.username,at:new Date().toISOString()};delete s.linkCodes[m[1]];save(s);return reply(id,'✅ Telegram linked to your SANKI account. Expense updates will arrive here.');}
  if(/^\/stop\b/i.test(raw)){delete s.chats[id];delete(s.chatMeta||{})[id];Object.keys(s.userChats).forEach(u=>{const left=chatIdsForUser(s,u).filter(x=>x!==String(id));if(left.length)s.userChats[u]=left;else delete s.userChats[u];});save(s);return reply(id,'🔕 This Telegram account was disconnected from SANKI notifications.');}
  const username=linkedUsername(s,id),target=username&&userSummary(username),isOwner=target&&target.roles&&target.roles.includes('owner');
  if(/^\/(?:accounts|menu)(?:@\w+)?\b/i.test(raw)||/^accounts menu$/i.test(raw))return sendAccountsMenu(id,target);
  const photos=Array.isArray(msg.photo)?msg.photo:[],anyDocument=msg.document||null,document=anyDocument&&/^image\//.test(String(anyDocument.mime_type||''))?anyDocument:null,file=(photos.length?photos[photos.length-1]:document),statementFile=anyDocument||(photos.length?photos[photos.length-1]:null),statementPrompt=s.bankStatementPrompts&&s.bankStatementPrompts[id];
  const accountPrompt=s.accountPrompts&&s.accountPrompts[id];if(accountPrompt&&accountPrompt.expiresAt>Date.now()){
    if(accountPrompt.action==='quick-paid-expense'){
      if(accountPrompt.phase==='proof'&&file){const download=await downloadPhoto(file.file_id,'quick-paid-expense'),sourceKey='telegram-quick-expense:'+id+':'+String(file.file_unique_id||file.file_id);let ocr={};try{ocr=await readPaymentScreenshot(download.filePath);}catch(err){console.error('[telegram] quick expense OCR failed:',err.message);}const suggestion=require('./expenses').telegramSuggestBusinessCategory((ocr.recipient||'')+' '+(ocr.text||''));Object.assign(accountPrompt,{amount:ocr.amountConfidence?ocr.amount:0,vendor:ocr.recipient||'',particulars:ocr.recipient||'Paid expense',ledger:suggestion.confidence?suggestion.ledger:'',date:ocr.date||new Date().toISOString().slice(0,10),proof:download.url,sourceKey,ocrText:ocr.text||'',expiresAt:Date.now()+1800000});if(!(accountPrompt.amount>0)){accountPrompt.phase='amount';save(s);return reply(id,'I could not read the amount confidently. Reply with only the correct amount, for example: 720');}accountPrompt.phase='account';save(s);return sendQuickAccountChoice(id);}
      if(accountPrompt.phase==='proof')return reply(id,'Please attach the payment screenshot.');
      if(accountPrompt.phase==='amount'&&!file){const m=raw.match(/(?:₹\s*)?([0-9][0-9,]*(?:\.\d{1,2})?)/);if(!m||!(Number(m[1].replace(/,/g,''))>0))return reply(id,'Send only the correct amount, for example: 720');accountPrompt.amount=Number(m[1].replace(/,/g,''));accountPrompt.phase='account';save(s);return sendQuickAccountChoice(id);}
      if(accountPrompt.phase==='edit'&&!file){let m;if((m=raw.match(/^amount\s*[:=-]?\s*(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)$/i)))accountPrompt.amount=Number(m[1].replace(/,/g,''));else if((m=raw.match(/^vendor\s*[:=-]?\s*(.+)$/i)))accountPrompt.vendor=m[1].trim();else if((m=raw.match(/^(?:particulars?|purpose|narration)\s*[:=-]?\s*(.+)$/i)))accountPrompt.particulars=m[1].trim();else if((m=raw.match(/^entity\s*[:=-]?\s*(SANKI|SAMAST)$/i)))accountPrompt.nature=m[1].toUpperCase();else return reply(id,'Use Amount…, Vendor…, Particulars…, or Entity SANKI/SAMAST. Account and category are changed using buttons.');accountPrompt.expiresAt=Date.now()+1800000;save(s);return sendQuickExpensePreview(id,accountPrompt);}
      if(accountPrompt.phase==='account')return reply(id,'Select one of the three paying-account buttons above.');
      if(accountPrompt.phase==='review')return reply(id,'Use Confirm, Edit, or Cancel on the review message above.');
    }
    if(accountPrompt.phase==='details'&&!file){const parsed=parseNativeAction(accountPrompt.action,raw);if(!parsed)return reply(id,'I could not read that. '+nativeActionHelp(accountPrompt.action));const oldProof=accountPrompt.proof;Object.assign(accountPrompt,parsed,{expiresAt:Date.now()+1800000});if(oldProof){accountPrompt.proof=oldProof;accountPrompt.phase='review';save(s);return sendNativeActionPreview(id,accountPrompt);}accountPrompt.phase='proof';save(s);return reply(id,'Now attach the proof/payment screenshot. Nothing is recorded yet.');}
    if(accountPrompt.phase==='proof'&&file){const download=await downloadPhoto(file.file_id,'account-tg');accountPrompt.proof=download.url;accountPrompt.phase='review';accountPrompt.expiresAt=Date.now()+1800000;save(s);return sendNativeActionPreview(id,accountPrompt);}
    if(accountPrompt.phase==='proof')return reply(id,'Please attach the proof/payment screenshot.');
    if(accountPrompt.phase==='review')return reply(id,'Use Confirm, Edit, or Cancel on the review message above.');
  }
  const namedTransfer=s.transferPrompts&&s.transferPrompts[id];if(namedTransfer&&namedTransfer.expiresAt>Date.now()&&(namedTransfer.phase==='details'||namedTransfer.phase==='edit')&&!file){const m=raw.match(/^(Namita Cash|\d{4})\s+(?:to|>|→)\s+(Namita Cash|\d{4})\s+(?:₹\s*)?([0-9][0-9,]*(?:\.\d{1,2})?)(?:\s+(.+))?$/i);if(m&&(/namita/i.test(m[1])||/namita/i.test(m[2]))){const editing=namedTransfer.phase==='edit';namedTransfer.fromAccount=m[1];namedTransfer.toAccount=m[2];namedTransfer.amount=Number(m[3].replace(/,/g,''));namedTransfer.note=String(m[4]||'').trim();namedTransfer.date=new Date().toISOString().slice(0,10);namedTransfer.phase=editing&&namedTransfer.proof?'review':'proof';save(s);if(namedTransfer.phase==='proof')return reply(id,'Now attach the transfer payment screenshot. Nothing is recorded yet.');return tg('sendMessage',{chat_id:id,text:'<b>Confirm corrected transfer</b>\n\nFrom: <b>'+esc(namedTransfer.fromAccount)+'</b>\nTo: <b>'+esc(namedTransfer.toAccount)+'</b>\nAmount: <b>'+money(namedTransfer.amount)+'</b>\nNote: '+esc(namedTransfer.note||'—')+'\nDate: '+esc(namedTransfer.date),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm transfer',callback_data:'am:transfer-confirm'},{text:'✏️ Edit',callback_data:'am:transfer-edit'}],[{text:'❌ Cancel',callback_data:'am:transfer-cancel'}]]}});}}
  const transferPrompt=s.transferPrompts&&s.transferPrompts[id];if(transferPrompt&&transferPrompt.expiresAt>Date.now()&&!(target&&target.roles||[]).includes('owner')){delete s.transferPrompts[id];save(s);return reply(id,'Only the Owner can record general account transfers.');}if(transferPrompt&&transferPrompt.expiresAt>Date.now()){
    const roleList=target&&target.roles||[];if(!roleList.some(x=>['owner','admin'].includes(x)))return reply(id,'Only the Owner or Admin can record transfers.');if((transferPrompt.phase==='details'||transferPrompt.phase==='edit')&&!file){const editing=transferPrompt.phase==='edit',m=raw.match(/^(?:transfer\s+)?(\d{4})\s+(?:to|>|→)\s+(\d{4})\s+(?:₹\s*)?([0-9][0-9,]*(?:\.\d{1,2})?)(?:\s+(.+))?$/i);if(!m)return reply(id,'Use this easy format:\n3448 to 3645 5000 Office funds');transferPrompt.fromAccount=m[1];transferPrompt.toAccount=m[2];transferPrompt.amount=Number(m[3].replace(/,/g,''));transferPrompt.note=String(m[4]||'').trim();transferPrompt.date=new Date().toISOString().slice(0,10);transferPrompt.phase=editing&&transferPrompt.proof?'review':'proof';save(s);if(transferPrompt.phase==='proof')return reply(id,'Now attach the transfer payment screenshot here. Nothing is recorded yet.');return tg('sendMessage',{chat_id:id,text:'<b>Confirm corrected transfer</b>\n\nFrom: <b>'+esc(transferPrompt.fromAccount)+'</b>\nTo: <b>'+esc(transferPrompt.toAccount)+'</b>\nAmount: <b>'+money(transferPrompt.amount)+'</b>\nNote: '+esc(transferPrompt.note||'—')+'\nDate: '+esc(transferPrompt.date),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm transfer',callback_data:'am:transfer-confirm'},{text:'✏️ Edit',callback_data:'am:transfer-edit'}],[{text:'❌ Cancel',callback_data:'am:transfer-cancel'}]]}});}if(transferPrompt.phase==='proof'&&file){const download=await downloadPhoto(file.file_id,'transfer-tg');transferPrompt.proof=download.url;transferPrompt.phase='review';transferPrompt.expiresAt=Date.now()+1800000;save(s);return tg('sendMessage',{chat_id:id,text:'<b>Confirm transfer</b>\n\nFrom: <b>'+esc(transferPrompt.fromAccount)+'</b>\nTo: <b>'+esc(transferPrompt.toAccount)+'</b>\nAmount: <b>'+money(transferPrompt.amount)+'</b>\nNote: '+esc(transferPrompt.note||'—')+'\nDate: '+esc(transferPrompt.date),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Confirm transfer',callback_data:'am:transfer-confirm'},{text:'✏️ Edit',callback_data:'am:transfer-edit'}],[{text:'❌ Cancel',callback_data:'am:transfer-cancel'}]]}});}if(transferPrompt.phase==='proof')return reply(id,'Please attach the transfer payment screenshot.');if(transferPrompt.phase==='review')return reply(id,'Use Confirm transfer, Edit, or Cancel on the transfer preview above.');}
  if(statementFile&&statementPrompt&&statementPrompt.expiresAt>Date.now()){
    const roleList=target&&target.roles||[];if(!roleList.some(x=>['owner','admin'].includes(x)))return reply(id,'Only the Owner or Admin can upload bank statements.');const natureMatch=raw.match(/\b(SANKI|SAMAST|PERSONAL)\b/i),accountMatch=raw.match(/\b(\d{4})\b/);if(!natureMatch||!accountMatch)return reply(id,'Add the entity and account last four digits as the caption, for example: SANKI 3645');const nature=natureMatch[1].toUpperCase(),expenses=require('./expenses'),account=expenses.telegramResolveAccount(nature,accountMatch[1]);if(!account)return reply(id,'That account was not recognized for '+nature+'. Check the last four digits and try again.');try{const download=await downloadPhoto(statementFile.file_id,'bank-statement',path.join(DIR,'bank-statements')),originalName=String(anyDocument&&anyDocument.file_name||download.filePath),imported=await expenses.importBankStatementUpload({filePath:download.filePath,originalName,account,nature,username:target.username,device:'Telegram'});if(!imported.success)return reply(id,imported.error);const checked=expenses.reconcileBankStatementAccount(account,target.username,'Telegram'),summary=checked.summary||{};delete s.bankStatementPrompts[id];save(s);return tg('sendMessage',{chat_id:id,text:'✅ <b>Statement imported and reconciled</b>\n'+esc(nature)+' · '+esc(account)+'\n\nRows read: '+imported.import.rows+'\nNew rows: '+imported.import.added+'\nAlready known: '+imported.import.updated+'\nMatched: '+(summary.matched||0)+'\nPossible matches: '+(summary.possible_match||0)+'\nMissing in app: '+(summary.missing_in_app||0)+'\nMissing in bank: '+(summary.missing_in_bank||0)+'\n\n'+(checked.reconciled?'Everything matches.':'Differences need review. Nothing unmatched was automatically recorded.'),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'Review reconciliation',url:base()+'/expenses.html?tab=accounts'}],[{text:'⬅️ Accounts menu',callback_data:'am:home'}]]}});}catch(e){return reply(id,'Could not read this statement: '+String(e.message||e));}
  }
  const approvalDraft=s.businessDrafts&&s.businessDrafts[id];if(!file&&approvalDraft&&approvalDraft.kind==='approval'&&approvalDraft.expiresAt>Date.now()){if(!businessEdit(approvalDraft,raw))return reply(id,'Use: Category…, Amount…, Vendor…, Particulars…, Entity…, Type…, or Payment type…');save(s);return sendBusinessPreview(id,approvalDraft);}
  const paymentEditKey=Object.keys(s.businessDrafts||{}).find(k=>s.businessDrafts[k]&&s.businessDrafts[k].phase==='payment-edit'&&String(s.businessDrafts[k].chatId)===id);if(!file&&paymentEditKey){const d=s.businessDrafts[paymentEditKey];let m;if((m=raw.match(/^amount\s*[:=-]?\s*(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)$/i)))d.amount=Number(m[1].replace(/,/g,''));else if((m=raw.match(/^account\s*[:=-]?\s*(cash|[0-9]{2,4})$/i)))d.account=m[1];else return reply(id,'Use Amount 500 or Account 3645.');d.phase='review';save(s);return sendPaymentPreview(id,paymentEditKey,d);}
  const replied=msg.reply_to_message&&msg.reply_to_message.message_id,promptKey=id+':'+replied,promptExpense=replied&&s.paymentPrompts[promptKey];if(file&&promptExpense){const e=require('./expenses').telegramExpense(promptExpense);if(!e){delete s.paymentPrompts[promptKey];save(s);return reply(id,'That expense no longer exists.');}const outstanding=Math.max(0,Number(e.amount||0)-Number(e.paidAmount||0));if(e.status==='paid'||outstanding<=0){delete s.paymentPrompts[promptKey];save(s);return reply(id,'✅ '+promptExpense+' is already fully paid. This screenshot was not recorded.');}if(!['approved','partially_paid'].includes(e.status)||e.paidAlready){delete s.paymentPrompts[promptKey];save(s);return reply(id,promptExpense+' is no longer awaiting a vendor payment. This screenshot was not recorded.');}const download=await downloadPhoto(file.file_id,'payment-tg'),sourceKey='telegram-payment:'+id+':'+String(file.file_unique_id||file.file_id);let ocr={};try{ocr=await readPaymentScreenshot(download.filePath);}catch(err){console.error('[telegram] payment OCR failed:',err.message);}const key=crypto.randomBytes(5).toString('hex'),draft={kind:'payment',expenseId:promptExpense,amount:ocr.amount||outstanding,account:ocr.account||'',date:ocr.date||new Date().toISOString().slice(0,10),proof:download.url,sourceKey,expiresAt:Date.now()+1800000,chatId:id};s.businessDrafts[key]=draft;delete s.paymentPrompts[promptKey];save(s);return sendPaymentPreview(id,key,draft);}
  if(file&&personalConfigured())return reply(id,'🔒 PERSONAL screenshots now belong in @'+(s.personalBotUsername||'personal5665_bot')+'. This file was not recorded.');
  const pending=s.pendingCaptures&&s.pendingCaptures[id];if(!file&&pending&&pending.expiresAt>Date.now()&&isOwner){if(pending.phase==='edit'){if(!applyCaptureEdit(pending,raw))return reply(id,'Use one of these formats:\nAmount 5000\nAccount 0993\nParticulars Food restaurant\nCategory Food & Dining');save(s);return sendCapturePreview(id,pending);}const answer=pending.missing==='account'?raw.match(/\bcash\b|\b\d{2,4}\b/i):raw.match(/\b[0-9][0-9,]*(?:\.\d{1,2})?\b/),value=answer&&answer[0];if(!value)return reply(id,'Please send only the requested '+(pending.missing==='account'?'account last digits, for example 0993.':'amount, for example 200.'));if(pending.missing==='account')pending.payload.account=value;else pending.payload.amount=Number(value.replace(/,/g,''));pending.missing=!(pending.payload.amount>0)?'amount':(!pending.payload.account?'account':'');save(s);if(pending.missing)return reply(id,'I still need the '+pending.missing+'. Please reply with only '+(pending.missing==='account'?'the account last digits, for example 0993.':'the amount, for example 200.'));return sendCapturePreview(id,pending);}
  if(file){
    if(msg.chat.type&&msg.chat.type!=='private')return reply(id,'🔒 Personal expense capture works only in your private bot chat.');
    if(!isOwner)return reply(id,'🔒 Only the linked Owner account can create PERSONAL expenses from Telegram.');
    const intent=parsePersonalIntent(raw);if(!intent.ok)return reply(id,'Could not record this yet: '+intent.error+'\n\nEasy format: Food tip');
    const supplied=parsePersonalCaption(raw),download=await downloadPhoto(file.file_id),sourceKey='telegram:'+id+':'+String(file.file_unique_id||file.file_id);let ocr={};try{ocr=await readPaymentScreenshot(download.filePath);}catch(e){console.error('[telegram] OCR failed:',e.message);}
    if(intent.received){const receiptOcr=parseReceiptOcr(ocr.text||''),amount=intent.amount||receiptOcr.amount,account=intent.cash?'cash':receiptOcr.account,date=receiptOcr.date||'',source=intent.particulars,payload={amount,account,date,source,proof:download.url,sourceKey,ocrText:receiptOcr.text};if(!(amount>0)||!account){const missing=!(amount>0)?'amount':'account';s.pendingCaptures[id]={kind:'receipt',missing,payload,expiresAt:Date.now()+1800000};save(s);return reply(id,'I could not read the '+missing+'. Please reply with only '+(missing==='account'?'the account last digits, for example 0993.':'the amount, for example 200.'));}const draft={kind:'receipt',payload,expiresAt:Date.now()+1800000};s.pendingCaptures[id]=draft;save(s);return sendCapturePreview(id,draft);}
    const trustedNarrationAmount=intent.amount||(supplied.ok&&supplied.amount),amount=trustedNarrationAmount||(ocr.amountConfidence?ocr.amount:0),account=intent.cash?'cash':(supplied.ok?supplied.account:ocr.account),date=(supplied.ok&&supplied.date)||ocr.date||'',particulars=supplied.ok?supplied.particulars:intent.particulars,category=inferPersonalCategory(particulars,ocr.recipient),payload={amount,account,date,particulars,vendor:ocr.recipient||particulars,ledger:category.ledger,needsReview:!category.confidence||!ocr.amountConfidence,ocrText:ocr.text,proof:download.url,sourceKey,rawNarration:raw};
    if(!(amount>0)||!account){const missing=!(amount>0)?'amount':'account';s.pendingCaptures[id]={kind:'expense',missing,payload,expiresAt:Date.now()+1800000};save(s);return reply(id,'I could not read the '+missing+'. Please reply with only '+(missing==='account'?'the account last digits, for example 0993.':'the amount, for example 200.'));}
    const draft={kind:'expense',payload,expiresAt:Date.now()+1800000};s.pendingCaptures[id]=draft;save(s);return sendCapturePreview(id,draft);
  }
  if(username)return tg('sendMessage',{chat_id:id,text:'Choose Accounts for SANKI/SAMAST work, or attach a PERSONAL payment screenshot with a short caption like:\nFood tip\n\nFor cash: Cash Nanny salary 27500',reply_markup:{keyboard:[[{text:'Accounts menu'}]],resize_keyboard:true,one_time_keyboard:false}});
  return reply(id,'Ask the Owner for a fresh SANKI Telegram linking link.');
}
async function handlePersonalCallback(query,s){if(!query||!query.message||!query.message.chat)return;const id=String(query.message.chat.id),username=linkedPersonalUsername(s,id),target=username&&userSummary(username),r=target&&target.roles||[],isOwner=r.includes('owner'),isNamita=String(username||'').toLowerCase()==='namita',data=String(query.data||'');await tgPersonal('answerCallbackQuery',{callback_query_id:query.id});if(!isOwner&&!isNamita)return reply(id,'Only an authorised PERSONAL user can use this bot.',true);if(!isOwner&&(data.startsWith('ba:')||data.startsWith('bp:')))return reply(id,'Only the Owner can approve or settle PERSONAL expenses.',true);
  if(data.startsWith('ba:')){const parts=data.split(':'),action=parts[1],expenseId=parts[2],expenses=require('./expenses'),e=expenses.telegramExpense(expenseId);if(!e||String(e.nature).toUpperCase()!=='PERSONAL')return reply(id,'Only PERSONAL expenses can be handled in this bot.',true);const draftKey='personal:'+id;if(action==='categories'||action==='catpage'){const current=s.businessDrafts[draftKey];s.businessDrafts[draftKey]=current&&current.expenseId===expenseId?current:{kind:'personal-approval',expenseId,changes:{},expiresAt:Date.now()+1800000};s.businessDrafts[draftKey].expiresAt=Date.now()+1800000;save(s);const page=action==='catpage'?Number(parts[3]):0;return tgPersonal('sendMessage',{chat_id:id,text:'<b>Select a category before approval</b>\nPage '+(page+1),parse_mode:'HTML',reply_markup:approvalCategoryButtons(expenseId,page)});}if(action==='cat'){const index=Number(parts[3]),categories=expenses.telegramBusinessCategories(),category=categories[index];if(!category)return reply(id,'That category is not available.',true);const current=s.businessDrafts[draftKey],draft=current&&current.expenseId===expenseId?current:{kind:'personal-approval',expenseId,changes:{},expiresAt:Date.now()+1800000};draft.changes.ledger=category;draft.expiresAt=Date.now()+1800000;s.businessDrafts[draftKey]=draft;save(s);return sendPersonalApprovalPreview(id,draft);}if(action==='reject'){const out=expenses.telegramRejectExpense(expenseId,target.username);return reply(id,out.success?'❌ '+expenseId+' rejected.':out.error,true);}if(action==='cancel'){delete s.businessDrafts[draftKey];save(s);return reply(id,'Approval edit cancelled. Nothing changed.',true);}if(action==='edit'){const current=s.businessDrafts[draftKey];s.businessDrafts[draftKey]=current&&current.expenseId===expenseId?current:{kind:'personal-approval',expenseId,changes:{},expiresAt:Date.now()+1800000};s.businessDrafts[draftKey].expiresAt=Date.now()+1800000;save(s);return reply(id,'Reply with one correction at a time:\nCategory Food & Dining\nAmount 500\nVendor Vendor name\nParticulars Dinner\nType variable',true);}if(action==='approve'||action==='confirm'){const draft=s.businessDrafts[draftKey]&&s.businessDrafts[draftKey].expenseId===expenseId?s.businessDrafts[draftKey]:{changes:{}};const out=expenses.telegramApproveExpense(expenseId,target.username,draft.changes);if(!out.success){if(out.needsCategory){s.businessDrafts[draftKey]={kind:'personal-approval',expenseId,changes:{},expiresAt:Date.now()+1800000};save(s);return tgPersonal('sendMessage',{chat_id:id,text:'<b>Category is required before approval.</b>',parse_mode:'HTML',reply_markup:approvalCategoryButtons(expenseId,0)});}return reply(id,out.error,true);}delete s.businessDrafts[draftKey];save(s);return sendPersonalPaymentOptions(id,out.expense);}}
  if(data.startsWith('bp:')){const parts=data.split(':'),action=parts[1],key=parts[2],expenses=require('./expenses');if(action==='later')return reply(id,'Payment left pending. You can return to this expense later.',true);if(action==='start'){const e=expenses.telegramExpense(key);if(!e||String(e.nature).toUpperCase()!=='PERSONAL')return reply(id,'PERSONAL expense '+key+' was not found.',true);const due=Math.max(0,Number(e.amount||0)-Number(e.paidAmount||0));if(e.status==='paid'||due<=0)return reply(id,'✅ '+key+' is already fully paid.',true);const sent=await tgPersonal('sendMessage',{chat_id:id,text:'Reply directly to this message with the payment screenshot for '+key+'.'});if(sent&&sent.ok){s.paymentPrompts['personal:'+id+':'+sent.result.message_id]=key;save(s);}return;}const draft=s.businessDrafts[key];if(!draft||draft.kind!=='personal-payment'||draft.expiresAt<Date.now())return reply(id,'This payment draft expired. Start Record payment again.',true);if(action==='cancel'){delete s.businessDrafts[key];save(s);return reply(id,'Payment draft cancelled. Nothing was recorded.',true);}if(action==='edit'){draft.phase='personal-payment-edit';save(s);return reply(id,'Reply with one correction:\nAmount 500\nAccount 0993',true);}if(action==='confirm'){const out=expenses.telegramRecordPayment(draft.expenseId,target.username,draft);if(!out.success)return reply(id,out.error,true);delete s.businessDrafts[key];save(s);return reply(id,'✅ Payment recorded for '+draft.expenseId+'\n'+money(out.payment.amount)+' from '+out.payment.account+'\nStatus: '+out.expense.status,true);}}
  const p=s.pendingCaptures&&s.pendingCaptures[id];if(!p||p.expiresAt<Date.now())return reply(id,'This PERSONAL draft has expired. Send the screenshot again.',true);if(data==='personal_cancel'){delete s.pendingCaptures[id];save(s);return reply(id,'❌ Draft cancelled. Nothing was recorded.',true);}if(data==='personal_edit'){p.phase='edit';save(s);return reply(id,'Reply with one correction at a time:\nAmount 5000\nAccount 0993\nParticulars Food restaurant\nCategory Food & Dining',true);}if(data==='personal_confirm'){const done=completePending(p,target);if(done.ok)delete s.pendingCaptures[id];save(s);return reply(id,done.text,true);}}
async function handlePersonalMessage(msg,s){if(!msg||!msg.chat)return;const id=String(msg.chat.id),raw=String(msg.caption||msg.text||'').trim(),start=raw.match(/^\/start(?:@\w+)?\s+([a-f0-9]{32})$/i),link=start&&s.personalLinkCodes[start[1]];if(link&&Date.now()<link.expiresAt){const key=String(link.username).toLowerCase(),ids=personalChatIdsForUser(s,key);if(!ids.includes(id))ids.push(id);s.personalUserChats[key]=ids;s.personalChats[id]={id,name:link.username,at:new Date().toISOString()};s.personalChatMeta[id]={id,name:link.username,telegramName:String(msg.chat.username?('@'+msg.chat.username):([msg.chat.first_name,msg.chat.last_name].filter(Boolean).join(' ')||'Telegram account')),at:new Date().toISOString()};delete s.personalLinkCodes[start[1]];save(s);return reply(id,'✅ Personal bot linked for '+link.username+'. Personal activity will stay here and will not use SANKIFIER.',true);}const username=linkedPersonalUsername(s,id),target=username&&userSummary(username),isOwner=target&&target.roles&&target.roles.includes('owner'),isNamita=String(username||'').toLowerCase()==='namita',isPersonalUser=isOwner||isNamita;if(/^\/start\b/i.test(raw)){if(!isPersonalUser)return reply(id,'This is a private PERSONAL accounting bot. Ask the Owner to generate your Personal-bot link.',true);return reply(id,'✅ SANKIFIER Personal is connected for '+(isNamita?'Namita':'Owner')+'. Send a payment screenshot with a short narration, for example: Food tip\n\nFor cash: Cash Nanny salary 27500',true);}if(!isPersonalUser)return reply(id,'🔒 Only an authorised PERSONAL user can use this bot.',true);
  const photos=Array.isArray(msg.photo)?msg.photo:[],document=msg.document&&/^image\//.test(String(msg.document.mime_type||''))?msg.document:null,file=photos.length?photos[photos.length-1]:document,draftKey='personal:'+id,approvalDraft=s.businessDrafts&&s.businessDrafts[draftKey];
  const paymentEditKey=Object.keys(s.businessDrafts||{}).find(k=>s.businessDrafts[k]&&s.businessDrafts[k].kind==='personal-payment'&&s.businessDrafts[k].phase==='personal-payment-edit'&&String(s.businessDrafts[k].chatId)===id);if(!file&&paymentEditKey){const d=s.businessDrafts[paymentEditKey];let m;if((m=raw.match(/^amount\s*[:=-]?\s*(?:₹|rs\.?|inr)?\s*([0-9][0-9,]*(?:\.\d{1,2})?)$/i)))d.amount=Number(m[1].replace(/,/g,''));else if((m=raw.match(/^account\s*[:=-]?\s*(cash|[0-9]{2,4})$/i)))d.account=m[1];else return reply(id,'Use Amount 500 or Account 0993.',true);d.phase='review';save(s);return sendPersonalPaymentPreview(id,paymentEditKey,d);}
  const replied=msg.reply_to_message&&msg.reply_to_message.message_id,promptKey='personal:'+id+':'+replied,promptExpense=replied&&s.paymentPrompts[promptKey];if(file&&promptExpense){const expenses=require('./expenses'),e=expenses.telegramExpense(promptExpense);if(!e||String(e.nature).toUpperCase()!=='PERSONAL'){delete s.paymentPrompts[promptKey];save(s);return reply(id,'That PERSONAL expense no longer exists.',true);}const outstanding=Math.max(0,Number(e.amount||0)-Number(e.paidAmount||0));if(e.status==='paid'||outstanding<=0){delete s.paymentPrompts[promptKey];save(s);return reply(id,'✅ '+promptExpense+' is already fully paid. This screenshot was not recorded.',true);}const download=await downloadPhoto(file.file_id,'personal-payment-tg',null,personalToken());let ocr={};try{ocr=await readPaymentScreenshot(download.filePath);}catch(err){console.error('[telegram-personal] payment OCR failed:',err.message);}const key='personal-pay-'+crypto.randomBytes(5).toString('hex'),draft={kind:'personal-payment',expenseId:promptExpense,amount:ocr.amount||outstanding,account:ocr.account||'',date:ocr.date||new Date().toISOString().slice(0,10),proof:download.url,sourceKey:'telegram-personal-payment:'+id+':'+String(file.file_unique_id||file.file_id),expiresAt:Date.now()+1800000,chatId:id,phase:'review'};s.businessDrafts[key]=draft;delete s.paymentPrompts[promptKey];save(s);return sendPersonalPaymentPreview(id,key,draft);}
  if(!file&&approvalDraft&&approvalDraft.kind==='personal-approval'&&approvalDraft.expiresAt>Date.now()){if(!businessEdit(approvalDraft,raw))return reply(id,'Use Category…, Amount…, Vendor…, Particulars…, or Type…',true);save(s);const e=require('./expenses').telegramExpense(approvalDraft.expenseId);return tgPersonal('sendMessage',{chat_id:id,text:businessPreview(e,approvalDraft.changes),parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:'✅ Save & approve',callback_data:'ba:confirm:'+approvalDraft.expenseId},{text:'✏️ Edit more',callback_data:'ba:edit:'+approvalDraft.expenseId}],[{text:'Cancel',callback_data:'ba:cancel:'+approvalDraft.expenseId}]]}});}
  const pending=s.pendingCaptures&&s.pendingCaptures[id];if(!file&&pending&&pending.expiresAt>Date.now()){if(pending.phase==='edit'){if(!applyCaptureEdit(pending,raw))return reply(id,'Use Amount 5000, Account 0993, Particulars Food restaurant, or Category Food & Dining',true);save(s);return sendCapturePreview(id,pending,true);}const answer=pending.missing==='account'?raw.match(/\bcash\b|\b\d{2,4}\b/i):raw.match(/\b[0-9][0-9,]*(?:\.\d{1,2})?\b/),value=answer&&answer[0];if(!value)return reply(id,'Please send only the requested '+pending.missing+'.',true);if(pending.missing==='account')pending.payload.account=value;else pending.payload.amount=Number(value.replace(/,/g,''));pending.missing=!(pending.payload.amount>0)?'amount':(!pending.payload.account?'account':'');save(s);if(pending.missing)return reply(id,'I still need the '+pending.missing+'.',true);return sendCapturePreview(id,pending,true);}
  if(!file)return reply(id,'Attach a PERSONAL payment screenshot with a short narration like: Food tip\n\nFor cash: Cash Nanny salary 27500',true);if(msg.chat.type&&msg.chat.type!=='private')return reply(id,'🔒 PERSONAL capture works only in your private bot chat.',true);const intent=parsePersonalIntent(raw);if(!intent.ok)return reply(id,'Could not record this yet: '+intent.error+'\n\nEasy format: Food tip',true);const supplied=parsePersonalCaption(raw),download=await downloadPhoto(file.file_id,'personal-tg',null,personalToken()),sourceKey='telegram-personal:'+id+':'+String(file.file_unique_id||file.file_id);let ocr={};try{ocr=await readPaymentScreenshot(download.filePath);}catch(e){console.error('[telegram-personal] OCR failed:',e.message);}if(intent.received){const receiptOcr=parseReceiptOcr(ocr.text||''),amount=intent.amount||receiptOcr.amount,account=intent.cash?'cash':receiptOcr.account,date=receiptOcr.date||'',payload={amount,account,date,source:intent.particulars,proof:download.url,sourceKey,ocrText:receiptOcr.text};if(!(amount>0)||!account){s.pendingCaptures[id]={kind:'receipt',missing:!(amount>0)?'amount':'account',payload,expiresAt:Date.now()+1800000};save(s);return reply(id,'I could not read the '+s.pendingCaptures[id].missing+'. Please reply with only that value.',true);}const draft={kind:'receipt',payload,expiresAt:Date.now()+1800000};s.pendingCaptures[id]=draft;save(s);return sendCapturePreview(id,draft,true);}const trustedNarrationAmount=intent.amount||(supplied.ok&&supplied.amount),amount=trustedNarrationAmount||(ocr.amountConfidence?ocr.amount:0),account=intent.cash?'cash':(supplied.ok?supplied.account:ocr.account),date=(supplied.ok&&supplied.date)||ocr.date||'',particulars=supplied.ok?supplied.particulars:intent.particulars,category=inferPersonalCategory(particulars,ocr.recipient),payload={amount,account,date,particulars,vendor:ocr.recipient||particulars,ledger:category.ledger,needsReview:!category.confidence||!ocr.amountConfidence,ocrText:ocr.text,proof:download.url,sourceKey,rawNarration:raw};if(!(amount>0)||!account){s.pendingCaptures[id]={kind:'expense',missing:!(amount>0)?'amount':'account',payload,expiresAt:Date.now()+1800000};save(s);return reply(id,'I could not read the '+s.pendingCaptures[id].missing+'. Please reply with only that value.',true);}const draft={kind:'expense',payload,expiresAt:Date.now()+1800000};s.pendingCaptures[id]=draft;save(s);return sendCapturePreview(id,draft,true);}
router.post('/api/telegram/webhook/:secret',express.json(),(req,res)=>{const s=load(),header=req.get('x-telegram-bot-api-secret-token')||'';if(!s.webhookSecret||(req.params.secret!==s.webhookSecret&&header!==s.webhookSecret))return res.status(403).end();s.updates++;save(s);const update=req.body||{},query=update.callback_query,msg=update.message||update.edited_message;res.json({ok:true});const work=query?handleCallback(query,s):handleWebhookMessage(msg,s);work.catch(e=>{console.error('[telegram] webhook update failed:',e.message);const chat=query&&query.message&&query.message.chat||msg&&msg.chat;if(chat)reply(String(chat.id),'Could not process that request. Please try again.');});});
router.post('/api/telegram/personal-webhook/:secret',express.json(),(req,res)=>{const s=load(),header=req.get('x-telegram-bot-api-secret-token')||'';if(!s.personalWebhookSecret||(req.params.secret!==s.personalWebhookSecret&&header!==s.personalWebhookSecret))return res.status(403).end();s.personalUpdates++;save(s);const update=req.body||{},query=update.callback_query,msg=update.message||update.edited_message;res.json({ok:true});const work=query?handlePersonalCallback(query,s):handlePersonalMessage(msg,s);work.catch(e=>{console.error('[telegram-personal] webhook update failed:',e.message);const chat=query&&query.message&&query.message.chat||msg&&msg.chat;if(chat)reply(String(chat.id),'Could not process that request. Please try again.',true);});});
router.post('/api/telegram/link',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});if(!configured())return res.json({success:true,configured:false,username:target.username,url:'',expiresInMinutes:15});const finish=botUsername=>{if(!botUsername)return res.json({success:false,configured:true,error:'Could not identify the configured Telegram bot.'});const s=load(),code=crypto.randomBytes(16).toString('hex');s.botUsername=botUsername;s.linkCodes[code]={username:target.username,approver:target.roles.some(r=>['admin','owner','accounting','samast_accounting'].includes(r)),expiresAt:Date.now()+900000};Object.keys(s.linkCodes).forEach(k=>{if(s.linkCodes[k].expiresAt<Date.now())delete s.linkCodes[k];});save(s);res.json({success:true,configured:true,username:target.username,url:'https://t.me/'+botUsername+'?start='+code,expiresInMinutes:15});};const known=load().botUsername;if(known)return finish(known);tg('getMe',{}).then(me=>finish(me&&me.ok?me.result.username:''));});
router.post('/api/telegram/personal-link',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});if(!target.roles.includes('owner')&&String(target.username).toLowerCase()!=='namita')return res.status(400).json({success:false,error:'Personal bot access is limited to Owner and Namita.'});if(!personalConfigured())return res.json({success:true,configured:false,username:target.username,url:'',expiresInMinutes:15});const finish=botUsername=>{if(!botUsername)return res.json({success:false,configured:true,error:'Could not identify the Personal Telegram bot.'});const s=load(),key=target.username.toLowerCase(),code=crypto.randomBytes(16).toString('hex');s.personalBotUsername=botUsername;s.personalLinkCodes[code]={username:target.username,expiresAt:Date.now()+900000};if(key==='namita'){const old=chatIdsForUser(s,key);delete s.userChats[key];old.forEach(id=>{delete s.chats[id];delete s.chatMeta[id];});}Object.keys(s.personalLinkCodes).forEach(k=>{if(s.personalLinkCodes[k].expiresAt<Date.now())delete s.personalLinkCodes[k];});save(s);res.json({success:true,configured:true,username:target.username,url:'https://t.me/'+botUsername+'?start='+code,expiresInMinutes:15,movedFromMainBot:key==='namita'});};const known=load().personalBotUsername;if(known)return finish(known);tgPersonal('getMe',{}).then(me=>finish(me&&me.ok?me.result.username:''));});
function linkedAccounts(s){return Object.keys(s.userChats||{}).map(username=>({username,count:chatIdsForUser(s,username).length,connections:chatIdsForUser(s,username).map((id,i)=>({chatId:id,label:(s.chatMeta&&s.chatMeta[id]&&s.chatMeta[id].telegramName)||('Telegram '+(i+1)),linkedAt:(s.chatMeta&&s.chatMeta[id]&&s.chatMeta[id].at)||''}))}));}
router.get('/api/telegram/status',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const s=load(),localUrl=base()+'/api/telegram/webhook/',accounts=linkedAccounts(s),common={subscribers:Object.keys(s.chats).length,linkedUsers:accounts.length,linkedConnections:allLinkedChatIds(s).length,linkedUsernames:accounts.map(x=>x.username),linkedAccounts:accounts,botUsername:s.botUsername||''};if(!configured())return res.json(Object.assign({success:true,configured:false,webhookSet:false,connectedToThisApp:false},common));Promise.all([tg('getMe',{}),tg('getWebhookInfo',{})]).then(([me,hook])=>{const currentUrl=hook&&hook.ok&&hook.result?String(hook.result.url||''):'';res.json(Object.assign({success:true,configured:true,webhookSet:!!currentUrl,connectedToThisApp:currentUrl.startsWith(localUrl),pendingUpdates:hook&&hook.ok&&hook.result?Number(hook.result.pending_update_count||0):null},common,{botUsername:me&&me.ok?me.result.username:common.botUsername}));}).catch(()=>res.status(502).json({success:false,error:'Could not inspect the Telegram bot.'}));});
router.get('/api/telegram/personal-status',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const s=load(),localUrl=base()+'/api/telegram/personal-webhook/';if(!personalConfigured())return res.json({success:true,configured:false,webhookSet:false,connectedToThisApp:false,botUsername:''});Promise.all([tgPersonal('getMe',{}),tgPersonal('getWebhookInfo',{})]).then(([me,hook])=>{if(!me||!me.ok)return res.status(502).json({success:false,configured:true,error:me&&me.description||'The Personal bot token is invalid.'});const currentUrl=hook&&hook.ok&&hook.result?String(hook.result.url||''):'';res.json({success:true,configured:true,botUsername:me.result.username,webhookSet:!!currentUrl,connectedToThisApp:currentUrl.startsWith(localUrl),pendingUpdates:hook&&hook.ok&&hook.result?Number(hook.result.pending_update_count||0):null,lastError:hook&&hook.ok&&hook.result?String(hook.result.last_error_message||''):''});}).catch(()=>res.status(502).json({success:false,error:'Could not inspect the Personal Telegram bot.'}));});
router.post('/api/telegram/setup',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});if(!configured())return res.json({success:false,error:'TELEGRAM_BOT_TOKEN is not configured on Railway.'});const s=load();if(!s.webhookSecret)s.webhookSecret=crypto.randomBytes(24).toString('hex');Promise.all([tg('getMe',{}),tg('setWebhook',{url:base()+'/api/telegram/webhook/'+s.webhookSecret,secret_token:s.webhookSecret,allowed_updates:['message','callback_query']})]).then(([me,hook])=>{if(me&&me.ok)s.botUsername=me.result.username;save(s);res.json(hook&&hook.ok?{success:true,botUsername:s.botUsername}:{success:false,error:(hook&&hook.description)||'Webhook setup failed.'});});});
router.post('/api/telegram/personal-setup',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});if(!personalConfigured())return res.json({success:false,error:'TELEGRAM_PERSONAL_BOT_TOKEN is not configured on Railway.'});const s=load();if(!s.personalWebhookSecret)s.personalWebhookSecret=crypto.randomBytes(24).toString('hex');Promise.all([tgPersonal('getMe',{}),tgPersonal('setWebhook',{url:base()+'/api/telegram/personal-webhook/'+s.personalWebhookSecret,secret_token:s.personalWebhookSecret,allowed_updates:['message','callback_query'],drop_pending_updates:false})]).then(([me,hook])=>{if(me&&me.ok)s.personalBotUsername=me.result.username;save(s);if(!me||!me.ok)return res.status(502).json({success:false,error:me&&me.description||'The Personal bot token is invalid.'});res.json(hook&&hook.ok?{success:true,botUsername:s.personalBotUsername}:{success:false,error:hook&&hook.description||'Personal webhook setup failed.'});});});
router.post('/api/telegram/test',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const username=String(req.body&&req.body.username||'').trim();if(username){const target=userSummary(username);if(!target)return res.status(404).json({success:false,error:'User not found.'});return notifyUser(target.username,'🔔 <b>Your SANKI Telegram notifications are working.</b>').then(r=>res.json(r.sent?{success:true,sent:r.sent,username:target.username}:{success:false,sent:0,error:'This user has not linked Telegram yet.'}));}notify('🔔 <b>SANKI Telegram notifications are working.</b>').then(r=>res.json({success:true,sent:r.sent}));});
router.post('/api/telegram/unlink',(req,res)=>{if(!owner(req))return res.status(403).json({success:false,error:'Owner only.'});const target=userSummary(req.body&&req.body.username);if(!target)return res.status(404).json({success:false,error:'User not found.'});const s=load(),key=target.username.toLowerCase(),ids=chatIdsForUser(s,key),requested=String(req.body&&req.body.chatId||''),remove=requested?ids.filter(id=>id===requested):ids;if(requested&&!remove.length)return res.status(404).json({success:false,error:'Telegram connection not found.'});const left=ids.filter(id=>!remove.includes(id));if(left.length)s.userChats[key]=left;else delete s.userChats[key];remove.forEach(id=>{delete s.chats[id];delete(s.chatMeta||{})[id];});save(s);res.json({success:true,username:target.username,wasLinked:remove.length>0,removed:remove.length,remaining:left.length});});
ensureWebhookUpdates();
module.exports={router,notify,notifyApprovers,notifyUser,notifyUserWithPhoto,notifyExpenseForApproval,esc,configured,parsePersonalCaption,parsePersonalIntent,parsePaymentOcr,parseReceiptOcr,inferPersonalCategory,readPaymentScreenshot,applyCaptureEdit,capturePreview,chatIdsForUser,linkedAccounts};
